/* js/data.js — Hornet's side of the game: the Needle, the Crests, the Tools, the Silk Skills
   and the other abilities, the damage modifiers and the items.
   GENERATED by tools/gen-data.js from kb/data/raw/ (hollowknight.wiki, fetched with npm run kb)
   and the game's text (patch 1.0.30000): not edited by hand. Change the generator and run npm run data.

     name, desc   { es, en } from the game's text; key = its key in the dump (CLAUDE.md, "Translations").
     hits         per level (0..4), a list of [damage, times]: "4+2+1" is [[4,1],[2,1],[1,1]], a Cogwork
                  Wheel is [[2,7]]. Damage per hit before the enemy's modifier and Hornet's (1 + Σ);
                  each hit is rounded on its own, half to even (the wiki's damage page).
     scale        which level applies, to the attack and to the enemy's modifier: 'kit' (the Crafting
                  Kit, for Tools) or 'needle' (the Needle, for Strikes, Silk Skills, Voltvessels'
                  spear and Flintslate's burn).
     bonus        bonus damage: ignores every modifier (Flintslate's burn, Pollip Pouch's venom).
     roundDown    the follow-up hits round down (Threefold Pin, the Twelfth Architect's Silkshot).
     ammo         per Tool Pouch level (0..4); null = no limit. refill: shards per use at a bench,
                  rosaries per shot, reserve = a reserve is spent first.
     slots        a Crest's [open, locked] per colour; locked ones open with Memory Lockets.
     strike       the Crest's Needle Strike; minHits = the Witch's hits when not all land.
     MODIFIERS    add = into (1 + Σ), mul = after it; to = 'needle' or 'skill'. */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});

  const NEEDLES = [
    { level: 0, name: { es: 'Aguja', en: 'Needle', key: 'INV_NAME_NAIL1' }, damage: 5 },
    {
      level: 1,
      name: { es: 'Aguja afilada', en: 'Sharpened Needle', key: 'INV_NAME_NAIL2' },
      damage: 9,
    },
    {
      level: 2,
      name: { es: 'Aguja resplandeciente', en: 'Shining Needle', key: 'INV_NAME_NAIL3' },
      damage: 13,
    },
    {
      level: 3,
      name: { es: 'Aguja de acerocolmena', en: 'Hivesteel Needle', key: 'INV_NAME_NAIL4' },
      damage: 17,
    },
    {
      level: 4,
      name: { es: 'Aguja de acero pálido', en: 'Pale Steel Needle', key: 'INV_NAME_NAIL5' },
      damage: 21,
    },
  ];

  const CRESTS = [
    {
      id: 'hunter',
      key: 'CREST_HUNTER',
      name: { es: 'Cazadora', en: 'Hunter', key: 'CREST_HUNTER_NAME' },
      desc: {
        es: 'Acechas a la presa y atacas con golpes letales.',
        en: 'Stalk prey and attack with lethal strikes.',
        key: 'CREST_HUNTER_DESC',
      },
      slots: { skill: 1, red: [1, 1], blue: [1, 1], yellow: [1, 1] },
      strike: { hits: [[[7, 2]], [[13, 2]], [[18, 2]], [[24, 2]], [[29, 2]]] },
      evolved: {
        es: 'Acechas a la presa y atacas con golpes letales. La concentración aumenta con los golpes sucesivos.',
        en: 'Stalk prey and attack with lethal strikes. Build focus with successive strikes.',
        key: 'CREST_HUNTER_UPGRADED_DESC',
      },
    },
    {
      id: 'reaper',
      key: 'CREST_REAPER',
      name: { es: 'Parca', en: 'Reaper', key: 'CREST_REAPER_NAME' },
      desc: {
        es: 'Atacas con fuertes tajos arqueados y obtienes seda adicional de los enemigos.',
        en: 'Attack with heavy, arcing slashes and reap additional Silk from enemies.',
        key: 'CREST_REAPER_DESC',
      },
      slots: { skill: 1, red: [1, 1], blue: [1, 1], yellow: [1, 1] },
      strike: { hits: [[[12, 1]], [[22, 1]], [[32, 1]], [[42, 1]], [[52, 1]]] },
    },
    {
      id: 'wanderer',
      key: 'CREST_PILGRIM',
      name: { es: 'Errante', en: 'Wanderer', key: 'CREST_PILGRIM_NAME' },
      desc: {
        es: 'Cortas rápida y ágilmente con golpes cortos y precisos.',
        en: 'Cut swiftly and nimbly with short, precise strikes.',
        key: 'CREST_PILGRIM_DESC',
      },
      slots: { skill: 1, red: [1, 0], blue: [0, 2], yellow: [2, 1] },
      strike: { hits: [[[3, 5]], [[5, 5]], [[7, 5]], [[9, 5]], [[12, 5]]] },
    },
    {
      id: 'beast',
      key: 'CREST_WARRIOR',
      name: { es: 'Bestia', en: 'Beast', key: 'CREST_WARRIOR_NAME' },
      desc: {
        es: 'Desgarras a los enemigos con tajos salvajes. Enlaza para entrar en una furia salvaje y robar vida de la presa.',
        en: 'Tear foes with savage slashes. Bind to enter a wild fury and steal life from prey.',
        key: 'CREST_WARRIOR_DESC',
      },
      slots: { skill: 1, red: [2, 0], blue: [0, 0], yellow: [0, 2] },
      strike: { hits: [[[12, 1]], [[22, 1]], [[32, 1]], [[42, 1]], [[52, 1]]] },
    },
    {
      id: 'witch',
      key: 'CREST_WITCH',
      name: { es: 'Bruja', en: 'Witch', key: 'CREST_WITCH_NAME' },
      desc: {
        es: 'Bates la aguja con movimientos amplios. Robas vida de los enemigos mediante raíces retorcidas.',
        en: 'Whip the needle in sweeping swings. Leech the life of foes through twisted roots.',
        key: 'CREST_WITCH_DESC',
      },
      slots: { skill: 1, red: [1, 1], blue: [1, 2], yellow: [0, 0] },
      strike: { hits: [[[4, 4]], [[7, 4]], [[10, 4]], [[14, 4]], [[17, 4]]], minHits: 2 },
    },
    {
      id: 'architect',
      key: 'CREST_TOOLMASTER',
      name: { es: 'Arquitecta', en: 'Architect', key: 'CREST_TOOLMASTER_NAME' },
      desc: {
        es: 'Giras la aguja como un tornillo, destrozando a los enemigos. Puedes gastar seda para fabricar nuevas herramientas rápidamente.',
        en: 'Spin the needle as a screw, shredding foes. Spend Silk to rapidly craft new tools.',
        key: 'CREST_TOOLMASTER_DESC',
      },
      slots: { skill: 0, red: [3, 0], blue: [0, 2], yellow: [0, 2] },
      strike: { hits: [[[3, 5]], [[5, 5]], [[8, 5]], [[10, 5]], [[13, 5]]] },
    },
    {
      id: 'shaman',
      key: 'CREST_SPELL',
      name: { es: 'Chamana', en: 'Shaman', key: 'CREST_SPELL_NAME' },
      desc: {
        es: 'Lanzas la hoja hacia delante y potencias las habilidades de seda con poderosas runas.',
        en: 'Cast the blade forward and strengthen Silk Skills with powerful runes.',
        key: 'CREST_SPELL_DESC',
      },
      slots: { skill: 3, red: [0, 0], blue: [0, 2], yellow: [0, 0] },
      strike: { hits: [[[12, 1]], [[21, 1]], [[30, 1]], [[39, 1]], [[48, 1]]] },
    },
  ];

  const OTHER_CRESTS = [
    { id: 'cloakless', name: { es: 'Cloakless Crest', en: 'Cloakless Crest' }, needle: 3 },
    { id: 'cursed', name: { es: 'Cursed Crest', en: 'Cursed Crest' }, silkCap: 3 },
  ];

  const VESTICREST = {
    id: 'vesticrest',
    key: 'UI_MSG_TITLE_EXTRASLOT',
    name: { es: 'Vestiblasón', en: 'Vesticrest', key: 'UI_MSG_TITLE_EXTRASLOT_NAME' },
    at: { yellow: 12, blue: 20, hunter3: 27, sylphsong: 32 },
  };

  const TOOLS = [
    {
      id: 'straight-pin',
      key: 'STRAIGHT_PIN',
      color: 'red',
      name: { es: 'Alfiler recto', en: 'Straight Pin', key: 'STRAIGHT_PIN_NAME' },
      desc: {
        es: 'Herramienta arrojadiza ligera, diseñada para ataques rápidos.',
        en: 'Light throwing tool, designed for rapid attacks.',
        key: 'STRAIGHT_PIN_DESC',
      },
      ammo: [12, 15, 18, 21, 24],
      refill: { shards: 3.33 },
      attacks: [{ scale: 'kit', hits: [[[5, 1]], [[8, 1]], [[11, 1]], [[14, 1]], [[17, 1]]] }],
    },
    {
      id: 'threefold-pin',
      key: 'TRI_PIN',
      color: 'red',
      name: { es: 'Alfiler triple', en: 'Threefold Pin', key: 'TRI_PIN_NAME' },
      desc: {
        es: 'Arma plana, en capas, fabricada para arrojarla como conjunto.',
        en: 'Flat, layered weapon, crafted to be thrown in a set.',
        key: 'TRI_PIN_DESC',
      },
      ammo: [10, 12, 15, 17, 20],
      refill: { shards: 4 },
      attacks: [
        {
          scale: 'kit',
          roundDown: true,
          hits: [
            [[4, 1], [2, 1], [1, 1]],
            [[6, 1], [3, 1], [2, 1]],
            [[9, 1], [4, 1], [3, 1]],
            [[11, 1], [5, 1], [3, 1]],
            [[14, 1], [7, 1], [4, 1]],
          ],
        },
      ],
    },
    {
      id: 'sting-shard',
      key: 'STING_SHARD',
      color: 'red',
      name: { es: 'Aguijón cortante', en: 'Sting Shard', key: 'STING_SHARD_NAME' },
      desc: {
        es: 'Trampa letal formada por cuchillas fuertemente unidas. Una vez colocada, la trampa perforará a los enemigos que la toquen.',
        en: 'Lethal trap formed of tightly bound blades. Once placed, the trap will pierce enemies that come into contact.',
        key: 'STING_SHARD_DESC',
      },
      ammo: [6, 7, 9, 10, 12],
      refill: { shards: 6.66 },
      attacks: [
        {
          id: 'spike',
          name: { es: 'una púa', en: 'one spike' },
          scale: 'kit',
          hits: [[[4, 1]], [[6, 1]], [[9, 1]], [[11, 1]], [[14, 1]]],
        },
        {
          id: 'full',
          name: { es: 'golpe completo', en: 'full hit' },
          scale: 'kit',
          hits: [[[10, 1]], [[15, 1]], [[20, 1]], [[30, 1]], [[35, 1]]],
        },
      ],
    },
    {
      id: 'tacks',
      key: 'TACK',
      color: 'red',
      name: { es: 'Tachuelas', en: 'Tacks', key: 'TACK_NAME' },
      desc: {
        es: 'Cortos alfileres diseñados para esparcirlos por el suelo. Las puntas afiladas perforarán a cualquier enemigo que las pise.',
        en: 'Short pins designed to be scattered along the ground. The sharp points will pierce any enemy who steps upon them.',
        key: 'TACK_DESC',
      },
      ammo: [5, 6, 7, 8, 10],
      refill: { shards: 8 },
      attacks: [{ scale: 'kit', hits: [[[2, 8]], [[3, 8]], [[4, 8]], [[6, 8]], [[7, 8]]] }],
    },
    {
      id: 'longpin',
      key: 'HARPOON',
      color: 'red',
      name: { es: 'Alfiler largo', en: 'Longpin', key: 'HARPOON_NAME' },
      desc: {
        es: 'Alfiler con asta lastrado, capaz de perforar corazas duras.',
        en: 'Weighted pin and haft, formed to pierce tough shells.',
        key: 'HARPOON_DESC',
      },
      ammo: [10, 12, 15, 17, 20],
      refill: { shards: 4 },
      attacks: [{ scale: 'kit', hits: [[[5, 1]], [[8, 1]], [[11, 1]], [[14, 1]], [[17, 1]]] }],
    },
    {
      id: 'curveclaw',
      key: 'CURVE_CLAWS',
      color: 'red',
      name: { es: 'Garracurva', en: 'Curveclaw', key: 'CURVE_CLAWS_NAME' },
      desc: {
        es: 'Hueso afilado con forma de arco utilizado por los cazadores para derribar presas voladoras.',
        en: 'Arched sharpbone used by hunters to take down flying prey.',
        key: 'CURVE_CLAWS_DESC',
      },
      ammo: [8, 10, 12, 14, 16],
      refill: { shards: 5 },
      attacks: [{ scale: 'kit', hits: [[[3, 1]], [[5, 1]], [[7, 1]], [[8, 1]], [[10, 1]]] }],
      upgrade: 'curvesickle',
    },
    {
      id: 'curvesickle',
      key: 'CURVE_CLAWS_UPG',
      color: 'red',
      name: { es: 'Hozcurva', en: 'Curvesickle', key: 'CURVE_CLAWS_UPG_NAME' },
      desc: {
        es: 'Radio afilado utilizado por los cazadores para abatir presas peligrosas.',
        en: 'Radial sharpbone used by skilled hunters to take down dangerous prey.',
        key: 'CURVE_CLAWS_UPG_DESC',
      },
      ammo: [8, 10, 12, 14, 16],
      refill: { shards: 5 },
      attacks: [{ scale: 'kit', hits: [[[5, 1]], [[8, 1]], [[11, 1]], [[14, 1]], [[17, 1]]] }],
      upgradeOf: 'curveclaw',
    },
    {
      id: 'throwing-ring',
      key: 'SHAKRA_RING',
      color: 'red',
      name: { es: 'Anillo arrojadizo', en: 'Throwing Ring', key: 'SHAKRA_RING_NAME' },
      desc: {
        es: 'Arma arrojadiza endurecida de la guerrera Shakra. Arma de fuerza contundente que rebota entre enemigos y superficies duras.',
        en: 'Hardened throwing weapon of the warrior Shakra. Blunt force weapon that rebounds between enemies and hard surfaces.',
        key: 'SHAKRA_RING_DESC',
      },
      ammo: [10, 12, 15, 17, 20],
      refill: { shards: 4 },
      attacks: [{ scale: 'kit', hits: [[[4, 1]], [[6, 1]], [[9, 1]], [[11, 1]], [[14, 1]]] }],
    },
    {
      id: 'pimpillo',
      key: 'PIMPILO',
      color: 'red',
      name: { es: 'Alfimohada', en: 'Pimpillo', key: 'PIMPILO_NAME' },
      desc: {
        es: 'Bolsita de tela llena de material volátil. Explota al impactar contra los enemigos o mediante mecha.',
        en: 'Fabric pouch filled with volatile material. Explodes on impact with enemies or when ignited by its fuse.',
        key: 'PIMPILO_DESC',
      },
      ammo: [4, 5, 6, 7, 8],
      refill: { shards: 10 },
      attacks: [{ scale: 'kit', hits: [[[15, 1]], [[24, 1]], [[33, 1]], [[42, 1]], [[51, 1]]] }],
    },
    {
      id: 'conchcutter',
      key: 'CONCH_DRILL',
      color: 'red',
      name: { es: 'Cortaconcha', en: 'Conchcutter', key: 'CONCH_DRILL_NAME' },
      desc: {
        es: 'Arma en espiral fabricada con una punta de concha endurecida. Lanzada en ángulo, puede rebotar y pillar a la presa desprevenida.',
        en: 'Spiral weapon fashioned from a hardened conchspire. Thrown at an angle, it can ricochet and catch prey off guard.',
        key: 'CONCH_DRILL_DESC',
      },
      ammo: [8, 10, 12, 14, 16],
      refill: { shards: 5 },
      attacks: [{ scale: 'kit', hits: [[[2, 6]], [[3, 6]], [[4, 6]], [[6, 6]], [[7, 6]]] }],
    },
    {
      id: 'silkshot',
      key: 'SILKSHOT',
      color: 'red',
      name: { es: 'Honda sedeña', en: 'Silkshot', key: 'SILKSHOT_NAME' },
      ammo: [8, 10, 12, 14, 16],
      refill: { shards: 5 },
      attacks: [
        {
          id: 'forge',
          name: { es: 'Hija de la Forja', en: 'Forge Daughter' },
          desc: {
            es: 'Antigua arma de las Tejedoras, reparada y modificada por la Hija de la Forja. Utiliza cartuchos de coraza y la propia seda del portador para disparar.',
            en: 'Ancient weapon of the Weavers, repaired and modified by Forge Daughter. Uses shell canisters and the wielder\'s own Silk to fire.',
            key: 'SILKSHOT_DESC_FORGE',
          },
          scale: 'kit',
          hits: [[[6, 1]], [[10, 1]], [[13, 1]], [[17, 1]], [[20, 1]]],
        },
        {
          id: 'architect',
          name: { es: 'Duodécimo Arquitecto', en: 'Twelfth Architect', key: 'ARCHITECT_SHOP_TITLE' },
          desc: {
            es: 'Antigua arma de las Tejedoras, reparada y modificada por el Duodécimo Arquitecto. Utiliza cartuchos de coraza y la propia seda del portador para disparar.',
            en: 'Ancient weapon of the Weavers, repaired and modified by Twelfth Architect. Uses shell canisters and the wielder\'s own Silk to fire.',
            key: 'SILKSHOT_DESC_ARCHITECT',
          },
          scale: 'kit',
          roundDown: true,
          hits: [
            [[3, 1], [1, 1], [1, 1]],
            [[5, 1], [2, 1], [1, 1]],
            [[7, 1], [3, 1], [2, 1]],
            [[8, 1], [4, 1], [2, 1]],
            [[10, 1], [5, 1], [3, 1]],
          ],
        },
        {
          id: 'original',
          name: { es: 'Original', en: 'Original' },
          desc: {
            es: 'Antigua arma de las Tejedoras, reparada a su forma original. Utiliza cartuchos de coraza y la propia seda del portador para disparar.',
            en: 'Ancient weapon of the Weavers, repaired to its original form. Uses shell canisters and the wielder\'s own Silk to fire.',
            key: 'SILKSHOT_DESC_WEAVER',
          },
          scale: 'kit',
          hits: [[[10, 1]], [[16, 1]], [[22, 1]], [[28, 1]], [[34, 1]]],
        },
      ],
    },
    {
      id: 'delvers-drill',
      key: 'SCREWATTACK',
      color: 'red',
      name: { es: 'Taladro de excavador', en: 'Delver\'s Drill', key: 'SCREWATTACK_NAME' },
      desc: {
        es: 'Herramienta rotativa que sirve para perforar hueso y roca. Impulsa al que la empuña hacia abajo, mientras el taladro gira con una fuerza destructiva.',
        en: 'Rotary tool used for boring into bone and rock. Drives the wielder downwards, while spinning the drill with destructive force.',
        key: 'SCREWATTACK_DESC',
      },
      ammo: [9, 11, 13, 15, 18],
      refill: { shards: 4.44 },
      attacks: [{ scale: 'kit', hits: [[[4, 6]], [[6, 6]], [[9, 6]], [[11, 6]], [[14, 6]]] }],
    },
    {
      id: 'cogwork-wheel',
      key: 'COGWORK_SAW',
      color: 'red',
      name: { es: 'Rueda mecánica', en: 'Cogwork Wheel', key: 'COGWORK_SAW_NAME' },
      desc: {
        es: 'Hoja circular expansible accionada por un motor mecánico. Se propulsa hacia delante, cortando a los enemigos.',
        en: 'Expanding circular blade powered by a cogwork motor. Propels forward, slicing through foes.',
        key: 'COGWORK_SAW_DESC',
      },
      ammo: [5, 6, 7, 8, 10],
      refill: { shards: 8 },
      attacks: [{ scale: 'kit', hits: [[[2, 7]], [[3, 7]], [[4, 7]], [[6, 7]], [[7, 7]]] }],
    },
    {
      id: 'cogfly',
      key: 'COGWORK_FLIER',
      color: 'red',
      name: { es: 'Mosca mecánica', en: 'Cogfly', key: 'COGWORK_FLIER_NAME' },
      desc: {
        es: 'Compañero alado mecánico que busca y ataca a los enemigos cercanos.',
        en: 'Winged cogwork companion that will seek nearby foes and attack.',
        key: 'COGWORK_FLIER_DESC',
      },
      ammo: [4, 5, 6, 7, 8],
      refill: { shards: 10 },
      attacks: [{ scale: 'kit', hits: [[[3, 5]], [[5, 5]], [[7, 5]], [[8, 5]], [[10, 5]]] }],
    },
    {
      id: 'rosary-cannon',
      key: 'ROSARYCANNON',
      color: 'red',
      name: { es: 'Cañón de rosarios', en: 'Rosary Cannon', key: 'ROSARYCANNON_NAME' },
      desc: {
        es: 'Mecanismo reutilizado a partir de una máquina para ensartar rosarios. Para recargar el cañón, hay que introducir rosarios.',
        en: 'Repurposed mechanism from the base of a rosary stringing machine. Rosaries must be inserted to reload the cannon.',
        key: 'ROSARYCANNON_DESC',
      },
      ammo: [80, 80, 80, 80, 80],
      refill: { rosaries: 1 },
      attacks: [
        {
          id: 'high',
          name: { es: 'rosario alto', en: 'high rosary' },
          scale: 'kit',
          hits: [[[2, 1]], [[3, 1]], [[4, 1]], [[6, 1]], [[7, 1]]],
        },
        {
          id: 'low',
          name: { es: 'rosario bajo', en: 'low rosary' },
          scale: 'kit',
          hits: [[[1, 1]], [[2, 1]], [[2, 1]], [[3, 1]], [[3, 1]]],
        },
      ],
    },
    {
      id: 'voltvessels',
      key: 'LIGHTNING_ROD',
      color: 'red',
      name: { es: 'Recipientes voltaicos', en: 'Voltvessels', key: 'LIGHTNING_ROD_NAME' },
      desc: {
        es: 'Orbes convertibles que contienen electricidad. Los recipientes pueden lanzarse como boleadoras para causar una descarga explosiva o clavarse como una lanza para liberar una columna de energía.',
        en: 'Convertible orbs containing electricity. The vessels can be thrown as a bola for an explosive discharge or staked as a spear to release a column of energy.',
        key: 'LIGHTNING_ROD_DESC',
      },
      ammo: [5, 6, 7, 8, 10],
      refill: { shards: 8 },
      attacks: [
        {
          id: 'spear',
          name: { es: 'Lanza', en: 'Spear' },
          scale: 'needle',
          hits: [
            [[5, 1], [3, 6]],
            [[8, 1], [5, 6]],
            [[11, 1], [7, 6]],
            [[14, 1], [8, 6]],
            [[17, 1], [10, 6]],
          ],
        },
        {
          id: 'bola',
          name: { es: 'Boleadora', en: 'Bola' },
          scale: 'kit',
          hits: [
            [[5, 1], [3, 4]],
            [[5, 1], [5, 4]],
            [[5, 1], [7, 4]],
            [[5, 1], [8, 4]],
            [[5, 1], [10, 4]],
          ],
        },
      ],
    },
    {
      id: 'flintslate',
      key: 'FLINTSTONE',
      color: 'red',
      name: { es: 'Piedra de pedernal', en: 'Flintslate', key: 'FLINTSTONE_NAME' },
      desc: {
        es: 'Piedra de afilar fabricada con pedergema cortada y pulida. Sobrecalienta temporalmente la hoja de la aguja, lo que imbuye de llamas cada tajo y la hace más letal.',
        en: 'Sharpening slate made from cut and polished Flintgem. Temporarily super heats the needle\'s blade, imbuing each slash with flame and increasing lethality.',
        key: 'FLINTSTONE_DESC',
      },
      ammo: [3, 3, 4, 5, 6],
      refill: { shards: 13 },
      attacks: [
        {
          id: 'burn',
          scale: 'needle',
          bonus: true,
          hits: [[[1, 3]], [[2, 3]], [[3, 3]], [[3, 3]], [[4, 3]]],
        },
      ],
    },
    {
      id: 'snare-setter',
      key: 'SNARE',
      color: 'red',
      name: { es: 'Fijatrampas', en: 'Snare Setter', key: 'SNARE_NAME' },
      desc: {
        es: 'Herramienta para tender trampas de las Tejedoras. Coloca una runa de seda que prende fuego cuando la tocan los enemigos. Utiliza cartuchos de coraza y la propia seda del portador para disparar.',
        en: 'Trap-setting tool of the Weavers. Lays a Silk rune that ignites when foes come into contact. Uses shell canisters and the wielder\'s own Silk.',
        key: 'SNARE_DESC',
      },
      ammo: [5, 6, 7, 8, 10],
      refill: { shards: 8 },
      attacks: [
        {
          id: 'direct',
          name: { es: 'impacto directo', en: 'direct hit' },
          scale: 'kit',
          hits: [[[7, 1]], [[11, 1]], [[15, 1]], [[20, 1]], [[24, 1]]],
        },
        {
          id: 'snare',
          name: { es: 'trampa', en: 'snare' },
          scale: 'kit',
          hits: [[[25, 1]], [[40, 1]], [[55, 1]], [[70, 1]], [[85, 1]]],
        },
      ],
      lost: true,
    },
    {
      id: 'flea-brew',
      key: 'FLEA_BREW',
      color: 'red',
      name: { es: 'Brebaje pulgoso', en: 'Flea Brew', key: 'FLEA_BREW_NAME' },
      desc: {
        es: 'Bebida vigorizante preparada por la Caravana de las pulgas. Aumenta temporalmente la velocidad de movimiento y de ataque.',
        en: 'Invigorating beverage prepared by the Flea Caravan. Temporarily increases the speed of movement and attacks.',
        key: 'FLEA_BREW_DESC',
      },
      ammo: [3, 3, 4, 5, 6],
      refill: { shards: 10, reserve: true },
      attacks: [{ scale: 'kit', hits: [[[3, 1]], [[3, 1]], [[3, 1]], [[3, 1]], [[3, 1]]] }],
    },
    {
      id: 'plasmium-phial',
      key: 'SYRINGE_LIFEBLOOD',
      color: 'red',
      name: { es: 'Ampolla de plasmio', en: 'Plasmium Phial', key: 'SYRINGE_LIFEBLOOD_NAME' },
      desc: {
        es: 'Inyectadora con plasmio. Al inyectar el líquido, se puede ganar salud más allá de los límites naturales.',
        en: 'Spear-phial containing Plasmium. Injecting the liquid allows one to gain health beyond their natural limits.',
        key: 'SYRINGE_LIFEBLOOD_DESC',
      },
      ammo: [3, 3, 4, 5, 6],
      refill: { shards: 13.33, reserve: true },
    },
    {
      id: 'needle-phial',
      key: 'EXTRACTOR',
      color: 'red',
      name: { es: 'Ampolla con aguja', en: 'Needle Phial', key: 'EXTRACTOR_NAME' },
      desc: {
        es: 'Herramienta diseñada para extraer y almacenar fluidos. Para perforar su objetivo, la ampolla debe cargarse primero al máximo.',
        en: 'Tool designed to extract and store fluids. To pierce its target, the Needle Phial must first be charged to full tension.',
        key: 'EXTRACTOR_DESC',
      },
      ammo: null,
      refill: null,
      attacks: [{ scale: 'kit', hits: [[[7, 1]], [[11, 1]], [[15, 1]], [[20, 1]], [[24, 1]]] }],
      lost: true,
    },
    {
      id: 'druids-eye',
      key: 'MOSSCREEP_TOOL_1',
      color: 'blue',
      name: { es: 'Ojo del druida', en: 'Druid\'s Eye', key: 'MOSSCREEP_TOOL_1_NAME' },
      desc: {
        es: 'Amuleto de protección hecho con bayas musgosas. Cuando recibes daño, el amuleto segrega un elixir verde que se convierte en seda.',
        en: 'Amulet of protection formed from Mossberries. As the bearer takes damage, the amulet weeps a green elixir that will form into Silk.',
        key: 'MOSSCREEP_TOOL_1_DESC',
      },
      upgrade: 'druids-eyes',
    },
    {
      id: 'druids-eyes',
      key: 'MOSSCREEP_TOOL_2',
      color: 'blue',
      name: { es: 'Ojos del druida', en: 'Druid\'s Eyes', key: 'MOSSCREEP_TOOL_2_NAME' },
      desc: {
        es: 'Potente amuleto de protección hecho con muchas bayas musgosas. Cuando recibes daño, el amuleto segrega un elixir verde que se convierte en seda.',
        en: 'Powerful amulet of protection formed from many Mossberries. As the bearer takes damage, the amulet weeps a green elixir that will form into Silk.',
        key: 'MOSSCREEP_TOOL_2_DESC',
      },
      upgradeOf: 'druids-eye',
    },
    {
      id: 'magma-bell',
      key: 'LAVA_CHARM',
      color: 'blue',
      name: { es: 'Campana magmática', en: 'Magma Bell', key: 'LAVA_CHARM_NAME' },
      desc: {
        es: 'Campana de hierro forjado, fabricada para protegerse del intenso calor de los Muelles Profundos. Reduce el daño recibido de las llamas y la lava.',
        en: 'Forged iron bell, crafted to ward against the intense heat of the Deep Docks. Reduces the damage taken from flame and magma.',
        key: 'LAVA_CHARM_DESC',
      },
    },
    {
      id: 'warding-bell',
      key: 'BELL_BIND',
      color: 'blue',
      name: { es: 'Campana protectora', en: 'Warding Bell', key: 'BELL_BIND_NAME' },
      desc: {
        es: 'Campana sagrada inscrita con un himno de protección. Protege al portador mientras se cura las heridas.',
        en: 'Holy bell inscribed with a hymn of protection. Shields the bearer as they bind their wounds.',
        key: 'BELL_BIND_DESC',
      },
      attacks: [{ scale: 'kit', hits: [[[9, 1]], [[14, 1]], [[20, 1]], [[25, 1]], [[31, 1]]] }],
    },
    {
      id: 'pollip-pouch',
      key: 'POISON_POUCH',
      color: 'blue',
      name: { es: 'Bolsa pólipo', en: 'Pollip Pouch', key: 'POISON_POUCH_NAME' },
      desc: {
        es: 'Bolsita que contiene un veneno de acción rápida extraído del corazón de una flor. Aplica veneno a las herramientas equipadas.',
        en: 'Pouch containing a fast-acting venom drawn from a flower\'s heart. Applies venom to equipped tools.',
        key: 'POISON_POUCH_DESC',
      },
      attacks: [{ scale: 'kit', bonus: true, hits: [[[1, 1]], [[2, 1]], [[2, 1]], [[3, 1]], [[3, 1]]] }],
    },
    {
      id: 'fractured-mask',
      key: 'FRACTURED_MASK',
      color: 'blue',
      name: { es: 'Máscara fracturada', en: 'Fractured Mask', key: 'FRACTURED_MASK_NAME' },
      desc: {
        es: 'Cráneo de bicho tallado como protección. Previene el daño crítico, pero se rompe con el impacto. Si se rompe, la máscara se reparará al descansar en un banco.',
        en: 'Old bug\'s skull carved for protection. Shields against critical damage but shatters on impact. If shattered, the mask will be repaired while resting at a bench.',
        key: 'FRACTURED_MASK_DESC',
      },
    },
    {
      id: 'multibinder',
      key: 'MULTIBIND',
      color: 'blue',
      name: { es: 'Multihuso', en: 'Multibinder', key: 'MULTIBIND_NAME' },
      desc: {
        es: 'Elaborado huso de Tejedora grabado que solo pueden manejar quienes usan la seda. Prolonga el acto de enlazar, pero aumenta su efecto curativo.',
        en: 'Elaborate, etched Weaver spindle, usable only by wielders of Silk. Extends the act of binding, but increases its healing effect.',
        key: 'MULTIBIND_DESC',
      },
    },
    {
      id: 'weavelight',
      key: 'WHITE_RING',
      color: 'blue',
      name: { es: 'Tejeluz', en: 'Weavelight', key: 'WHITE_RING_NAME' },
      desc: {
        es: 'Aparato reluciente obra de Tejedoras. Su núcleo emite un tenue resplandor. Aumenta la velocidad de regeneración de seda.',
        en: 'Gleaming apparatus of Weaver make. Its core emits a faint glow. Increases the speed of Silk regeneration.',
        key: 'WHITE_RING_DESC',
      },
    },
    {
      id: 'sawtooth-circlet',
      key: 'BROLLYSPIKE',
      color: 'blue',
      name: { es: 'Anillo de dientes de sierra', en: 'Sawtooth Circlet', key: 'BROLLYSPIKE_NAME' },
      desc: {
        es: 'Cinturón flexible de dientes de sierra metálicos que puede fijarse al dobladillo de una capa. Al abrir la capa, las cuchillas giran y dañan a los enemigos cercanos.',
        en: 'Flexible belt of serrated metal teeth, able to be affixed to the hem of a cloak. Flaring the cloak will spin the blades, damaging surrounding enemies.',
        key: 'BROLLYSPIKE_DESC',
      },
      attacks: [
        {
          scale: 'kit',
          hits: [
            [[8, 1], [1, 1]],
            [[13, 1], [1, 1]],
            [[18, 1], [1, 1]],
            [[22, 1], [1, 1]],
            [[27, 1], [1, 1]],
          ],
        },
      ],
    },
    {
      id: 'injector-band',
      key: 'QUICKBIND',
      color: 'blue',
      name: { es: 'Banda inyectora', en: 'Injector Band', key: 'QUICKBIND_NAME' },
      desc: {
        es: 'Conjunto de alfileres quirúrgicos del Ala Blanca. Se utiliza para introducir seda a la fuerza en la coraza de un insecto. Aumenta la velocidad de enlace.',
        en: 'Brace of surgical pins from the Whiteward. Used to forcefully insert Silk deep inside a bug\'s shell. Increases the speed of binding.',
        key: 'QUICKBIND_DESC',
      },
    },
    {
      id: 'spool-extender',
      key: 'SPOOL_EXTENDER',
      color: 'blue',
      name: { es: 'Extensor de carrete', en: 'Spool Extender', key: 'SPOOL_EXTENDER_NAME' },
      desc: {
        es: 'Herramienta de la Ciudadela para almacenar seda, creada a partir de un artefacto de las Tejedoras. Permite ampliar el almacenaje de seda normal.',
        en: 'Silk-storing tool of the Citadel, fashioned after an artefact of the Weavers. Allows the storing of additional Silk beyond one\'s natural abilities.',
        key: 'SPOOL_EXTENDER_DESC',
      },
    },
    {
      id: 'reserve-bind',
      key: 'RESERVE_BIND',
      color: 'blue',
      name: { es: 'Reserva sedeña', en: 'Reserve Bind', key: 'RESERVE_BIND_NAME' },
      desc: {
        es: 'Artefacto ornamentado de la Ciudadela, capaz de almacenar seda suficiente para un enlace. Se usa cuando se necesita curación y los recursos naturales escasean. La reserva se restablece al descansar en un banco.',
        en: 'Ornate artefact of the Citadel, able to hold a Bind\'s worth of Silk. Used when healing is needed and one\'s natural resources run low. The Reserve Bind will be restored when resting at a bench.',
        key: 'RESERVE_BIND_DESC',
      },
    },
    {
      id: 'claw-mirror',
      key: 'DAZZLE_BIND',
      color: 'blue',
      name: { es: 'Garra espejo', en: 'Claw Mirror', key: 'DAZZLE_BIND_NAME' },
      desc: {
        es: 'Herramienta teatral de un bicho vanaglorioso. Al enlazar, emite un destello deslumbrante que daña a los enemigos circundantes.',
        en: 'Theatrical tool of a vainglorious bug. When binding, emits a dazzling flash that damages surrounding enemies.',
        key: 'DAZZLE_BIND_DESC',
      },
      attacks: [
        {
          scale: 'kit',
          hits: [
            [[11, 1], [5, 2]],
            [[18, 1], [5, 2]],
            [[24, 1], [5, 2]],
            [[31, 1], [5, 2]],
            [[37, 1], [5, 2]],
          ],
        },
      ],
      upgrade: 'claw-mirrors',
    },
    {
      id: 'claw-mirrors',
      key: 'DAZZLE_BIND_UPG',
      color: 'blue',
      name: { es: 'Garras espejo', en: 'Claw Mirrors', key: 'DAZZLE_BIND_UPG_NAME' },
      desc: {
        es: 'Herramientas teatrales gemelas de un bicho vanaglorioso. Al enlazar, emite una abrasadora ráfaga que daña a los enemigos circundantes.',
        en: 'Twin theatrical tools of a vainglorious bug. When binding, emits a searing blast that damages surrounding enemies.',
        key: 'DAZZLE_BIND_UPG_DESC',
      },
      attacks: [
        {
          scale: 'kit',
          hits: [
            [[15, 1], [8, 2]],
            [[24, 1], [8, 2]],
            [[33, 1], [8, 2]],
            [[42, 1], [8, 2]],
            [[51, 1], [8, 2]],
          ],
        },
      ],
      upgradeOf: 'claw-mirror',
    },
    {
      id: 'memory-crystal',
      key: 'REVENGE_CRYSTAL',
      color: 'blue',
      name: { es: 'Cristal de memoria', en: 'Memory Crystal', key: 'REVENGE_CRYSTAL_NAME' },
      desc: {
        es: 'Piedra reflectante con propiedades mnemotécnicas. Al recibir daño, se forma una memoria de cristal del portador. La memoria se romperá en espinas afiladas si un enemigo la toca.',
        en: 'Reflective stone with mnemonic properties. When taking damage, a memory of the bearer is formed of crystal. The memory will shatter into sharp spines if an enemy comes into contact.',
        key: 'REVENGE_CRYSTAL_DESC',
      },
      attacks: [{ scale: 'kit', hits: [[[10, 1]], [[16, 1]], [[22, 1]], [[28, 1]], [[34, 1]]] }],
    },
    {
      id: 'snitch-pick',
      key: 'THIEF_CLAW',
      color: 'blue',
      name: { es: 'Pico hurgón', en: 'Snitch Pick', key: 'THIEF_CLAW_NAME' },
      desc: {
        es: 'Herramienta con gancho para sacarles a la fuerza el botín a bichos y cáscaras. Al lanzarlo contra enemigos, roba rosarios y fragmentos de coraza, además de causar daño adicional.',
        en: 'Hooked tool for the forceful retrieval of loot from bugs and husks. Harpoon into foes to steal rosaries and shell shards, while causing additional damage.',
        key: 'THIEF_CLAW_DESC',
      },
    },
    {
      id: 'volt-filament',
      key: 'ZAP_IMBUEMENT',
      color: 'blue',
      name: { es: 'Filamento voltaico', en: 'Volt Filament', key: 'ZAP_IMBUEMENT_NAME' },
      desc: {
        es: 'Órgano cargado de un voltvyrm abatido. Puede enrollarse en un hilo, lo que imbuye una carga eléctrica a las habilidades de seda.',
        en: 'Charged organ from a defeated Voltvyrm. Can be coiled around thread, imbuing Silk Skills with electric charge.',
        key: 'ZAP_IMBUEMENT_DESC',
      },
    },
    {
      id: 'quick-sling',
      key: 'QUICK_SLING',
      color: 'blue',
      name: { es: 'Honda veloz', en: 'Quick Sling', key: 'QUICK_SLING_NAME' },
      desc: {
        es: 'Mecanismo de tracción construido con caña y hueso, diseñado para montarse en la extremidad de un bicho. Duplica el número de herramientas lanzadas.',
        en: 'Taut-drawing mechanism built from reed and bone, intended for mounting on the limb of a bug. Doubles the number of tools thrown.',
        key: 'QUICK_SLING_DESC',
      },
    },
    {
      id: 'wreath-of-purity',
      key: 'MAGGOT_CHARM',
      color: 'blue',
      name: { es: 'Corona de pureza', en: 'Wreath of Purity', key: 'MAGGOT_CHARM_NAME' },
      desc: {
        es: 'Frágil banda tejida con cáñamo y hojas, hecha para repeler a los gusasucios. Si se rompe, la corona se reparará al descansar en un banco.',
        en: 'Fragile band woven of reed and leaf, crafted to repel Muckmaggots. If broken, the wreath will be repaired while resting at a bench.',
        key: 'MAGGOT_CHARM_DESC',
      },
    },
    {
      id: 'longclaw',
      key: 'LONGNEEDLE',
      color: 'blue',
      name: { es: 'Garralarga', en: 'Longclaw', key: 'LONGNEEDLE_NAME' },
      desc: {
        es: 'Talismán fabricado con la garra de un gran depredador. Aumenta el alcance de los ataques con aguja.',
        en: 'Talisman fashioned from the talon of a large predator. Increases the range of needle attacks.',
        key: 'LONGNEEDLE_DESC',
      },
    },
    {
      id: 'wispfire-lantern',
      key: 'WISP_LANTERN',
      color: 'blue',
      name: { es: 'Farol de fuego fatuo', en: 'Wispfire Lantern', key: 'WISP_LANTERN_NAME' },
      desc: {
        es: 'Farol de hierro roto que contiene ardiente fuego fatuo. Del farol salen llamas fatuas que queman a los enemigos, a costa de seda.',
        en: 'Broken iron lantern containing smouldering wispfire. Wisps will spawn from the lantern and burn foes, at the cost of Silk.',
        key: 'WISP_LANTERN_DESC',
      },
      attacks: [{ scale: 'kit', hits: [[[5, 1]], [[8, 1]], [[11, 1]], [[14, 1]], [[17, 1]]] }],
    },
    {
      id: 'egg-of-flealia',
      key: 'FLEA_CHARM',
      color: 'blue',
      name: { es: 'Huevo de Pulgalia', en: 'Egg of Flealia', key: 'FLEA_CHARM_NAME' },
      desc: {
        es: 'Icono de la mítica madre pulga, transmitido por las caravanas de antaño. Es símbolo de protección y parentesco. Reduce el coste de las habilidades de seda cuando tienes la salud al máximo.',
        en: 'Icon of the mythical mother flea, passed down from caravans of old. A symbol of protection and kinship. Decreases the cost of Silk Skills while health is full.',
        key: 'FLEA_CHARM_DESC',
      },
    },
    {
      id: 'pin-badge',
      key: 'PINSTRESS',
      color: 'blue',
      name: { es: 'Placa de alfiler', en: 'Pin Badge', key: 'PINSTRESS_NAME' },
      desc: {
        es: 'Emblema de la orden de las Alfileras, las antiguas maestras de la cuchilla de Telalejana. Reduce el tiempo de carga de Golpe concentrado.',
        en: 'Emblem of the Order of the Pinstress, the old blademasters of Pharloom. Reduces charge time of Needle Strike.',
        key: 'PINSTRESS_DESC',
      },
    },
    {
      id: 'compass',
      key: 'COMPASS',
      color: 'yellow',
      name: { es: 'Brújula', en: 'Compass', key: 'COMPASS_NAME' },
      desc: {
        es: 'Intrincado dispositivo de rastreo tallado a partir de coraza. Una vez equipado, la ubicación del portador se marcará en su mapa.',
        en: 'Intricate tracking device, carved from shell. When equipped, the bearer\'s location will be marked on their map.',
        key: 'COMPASS_DESC',
      },
    },
    {
      id: 'shard-pendant',
      key: 'BONE_NECKLACE',
      color: 'yellow',
      name: { es: 'Colgante fragmentador', en: 'Shard Pendant', key: 'BONE_NECKLACE_NAME' },
      desc: {
        es: 'Tosca baratija que llevan los coleccionistas y artesanos. Permite recoger más fragmentos de coraza de las criaturas abatidas.',
        en: 'Crude trinket worn by collectors and crafters. Allows one to collect more shell shards from defeated creatures.',
        key: 'BONE_NECKLACE_DESC',
      },
    },
    {
      id: 'magnetite-brooch',
      key: 'ROSARY_MAGNET',
      color: 'yellow',
      name: { es: 'Broche de magnetita', en: 'Magnetite Brooch', key: 'ROSARY_MAGNET_NAME' },
      desc: {
        es: 'Piedra sagrada con una oración para rosarios inscrita. Atrae las cuentas sueltas hacia el portador.',
        en: 'Holy stone inscribed with a prayer for rosaries. Any loose beads will be pulled toward the wearer.',
        key: 'ROSARY_MAGNET_DESC',
      },
    },
    {
      id: 'weighted-belt',
      key: 'WEIGHTED_ANKLET',
      color: 'yellow',
      name: { es: 'Cinturón lastrado', en: 'Weighted Belt', key: 'WEIGHTED_ANKLET_NAME' },
      desc: {
        es: 'Banda pesada preferida por aquellos de paso inseguro. El portador retrocede menos al golpear a los enemigos y no sale despedido tan lejos al recibir daño.',
        en: 'Heavy band favoured by those with an unsteady step. The wearer will recoil less when striking foes and will not be flung as far when taking damage.',
        key: 'WEIGHTED_ANKLET_DESC',
      },
    },
    {
      id: 'barbed-bracelet',
      key: 'BARBED_WIRE',
      color: 'yellow',
      name: { es: 'Cilicio', en: 'Barbed Bracelet', key: 'BARBED_WIRE_NAME' },
      desc: {
        es: 'Cruel brazalete que llevan aquellos que creen que su castigo es insuficiente. Aumenta el daño recibido, pero también aumenta el daño infligido por la aguja.',
        en: 'Vicious bracelet worn by those who believe they have not been duly punished. Increases damage taken, but also increases damage dealt by the needle.',
        key: 'BARBED_WIRE_DESC',
      },
    },
    {
      id: 'dead-bugs-purse',
      key: 'DEAD_MANS_PURSE',
      color: 'yellow',
      name: { es: 'Bolsa de bicho muerto', en: 'Dead Bug\'s Purse', key: 'DEAD_MANS_PURSE_NAME' },
      desc: {
        es: 'Bolsa desechada de un peregrino caído. Permite al portador conservar algunos rosarios tras su derrota.',
        en: 'Discarded purse of a fallen pilgrim. Allows the bearer to retain some rosaries upon defeat.',
        key: 'DEAD_MANS_PURSE_DESC',
      },
    },
    {
      id: 'shell-satchel',
      key: 'SHELL_SATCHEL',
      color: 'yellow',
      name: { es: 'Saquito de coraza', en: 'Shell Satchel', key: 'SHELL_SATCHEL_NAME' },
      desc: {
        es: 'Contenedor de acceso rápido formado a partir de una vieja coraza. Aumenta la cantidad de herramientas fabricadas.',
        en: 'Quick access container formed from an old shell. Increases the quantity of crafted tools.',
        key: 'SHELL_SATCHEL_DESC',
      },
      steel: true,
      replaces: 'dead-bugs-purse',
    },
    {
      id: 'magnetite-dice',
      key: 'MAGNETITE_DICE',
      color: 'yellow',
      name: { es: 'Dados de magnetita', en: 'Magnetite Dice', key: 'MAGNETITE_DICE_NAME' },
      desc: {
        es: 'Juguetes tallados a partir de material magnético. Se usan en juegos sencillos y se cree que traen suerte a su portador.',
        en: 'Playthings carved from magnetic material. Used in simple games and believed to bring luck to the bearer.',
        key: 'MAGNETITE_DICE_DESC',
      },
    },
    {
      id: 'scuttlebrace',
      key: 'SCUTTLEBRACE',
      color: 'yellow',
      name: { es: 'Brazada de desliz', en: 'Scuttlebrace', key: 'SCUTTLEBRACE_NAME' },
      desc: {
        es: 'Espina artificial que se sujeta firmemente alrededor de la coraza. Aumenta la flexibilidad innata del portador, lo que permite una retirada rápida.',
        en: 'Artificial spine that clasps tight around the shell. Enhances the wearer\'s innate flexibility, allowing rapid retreat.',
        key: 'SCUTTLEBRACE_DESC',
      },
    },
    {
      id: 'ascendants-grip',
      key: 'WALLCLING',
      color: 'yellow',
      name: { es: 'Agarre del ascendente', en: 'Ascendant\'s Grip', key: 'WALLCLING_NAME' },
      desc: {
        es: 'Pitón dorado que permite sujetarse a una pared.',
        en: 'Gilded piton that allows one to hold in place while on a wall.',
        key: 'WALLCLING_DESC',
      },
    },
    {
      id: 'spider-strings',
      key: 'MUSICIAN_CHARM',
      color: 'yellow',
      name: { es: 'Cuerdas arácnidas', en: 'Spider Strings', key: 'MUSICIAN_CHARM_NAME' },
      desc: {
        es: 'Sofisticado dispositivo de las Tejedoras. Resuena con la música para amplificar y mejorar una actuación. Amplía y refuerza los efectos del Agujolín.',
        en: 'Sophisticated Weaver device. Resonates with music played to amplify and enhance a performance. Expands and strengthens the effects of the Needolin.',
        key: 'MUSICIAN_CHARM_DESC',
      },
    },
    {
      id: 'silkspeed-anklets',
      key: 'SPRINTMASTER',
      color: 'yellow',
      name: { es: 'Tobilleras rapisedeñas', en: 'Silkspeed Anklets', key: 'SPRINTMASTER_NAME' },
      desc: {
        es: 'Tobilleras experimentales, obra de las Tejedoras. Utilizan la propia seda del portador para aumentar la velocidad de esprint.',
        en: 'Experimental anklets of Weaver make. Draws upon the wearer\'s own Silk to increase sprinting speed.',
        key: 'SPRINTMASTER_DESC',
      },
    },
    {
      id: 'thiefs-mark',
      key: 'THIEF_CHARM',
      color: 'yellow',
      name: { es: 'Marca de ladrón', en: 'Thief\'s Mark', key: 'THIEF_CHARM_NAME' },
      desc: {
        es: 'Símbolo identificativo entre ladrones. Consigues rosarios adicionales al abatir enemigos, pero pierdes algunos rosarios al recibir daño.',
        en: 'Symbol worn to identify oneself to fellow thieves. Gain extra rosaries from defeated enemies, but lose some rosaries on taking damage.',
        key: 'THIEF_CHARM_DESC',
      },
    },
  ];

  const SKILLS = [
    {
      id: 'silkspear',
      key: 'INV_NAME_SKILL_THROW',
      name: { es: 'Lanza sedeña', en: 'Silkspear', key: 'INV_NAME_SKILL_THROW' },
      desc: {
        es: 'Técnica mortal de las Tejedoras. Lanza la aguja hacia delante con la fuerza amplificada por la seda enrollada.',
        en: 'Deadly Weaver technique. Throw the needle forward with force amplified by coiled Silk.',
        key: 'INV_DESC_SKILL_THROW',
      },
      silk: 4,
      attacks: [{ scale: 'needle', hits: [[[15, 1]], [[27, 1]], [[39, 1]], [[51, 1]], [[63, 1]]] }],
    },
    {
      id: 'thread-storm',
      key: 'INV_NAME_SKILL_SPHERE',
      name: { es: 'Tormenta de hilos', en: 'Thread Storm', key: 'INV_NAME_SKILL_SPHERE' },
      desc: {
        es: 'Técnica mortal de las Tejedoras. Lanza la aguja en un torbellino de seda a tu alrededor, azotando a los enemigos.',
        en: 'Deadly Weaver technique. Cast the needle in a whirl of Silk around oneself, lashing foes.',
        key: 'INV_DESC_SKILL_SPHERE',
      },
      silk: 4,
      attacks: [
        {
          scale: 'needle',
          hits: [
            [[4, 4], [1, 1]],
            [[7, 4], [2, 1]],
            [[10, 4], [3, 1]],
            [[13, 4], [4, 1]],
            [[16, 4], [5, 1]],
          ],
        },
        {
          id: 'extended',
          name: { es: 'prolongada', en: 'extended' },
          scale: 'needle',
          hits: [
            [[4, 4], [1, 1], [1, 6]],
            [[7, 4], [2, 1], [1, 6]],
            [[10, 4], [3, 1], [2, 6]],
            [[13, 4], [4, 1], [3, 6]],
            [[16, 4], [5, 1], [4, 6]],
          ],
        },
      ],
    },
    {
      id: 'cross-stitch',
      key: 'INV_NAME_SKILL_PARRY',
      name: { es: 'Punto de cruz', en: 'Cross Stitch', key: 'INV_NAME_SKILL_PARRY' },
      desc: {
        es: 'Técnica deflectora de una criatura hilada. Enlaza seda alrededor de la aguja para desviar los ataques enemigos y contraatacar al instante.',
        en: 'Deflective technique of a creature spun from thread. Bind Silk around the needle to deflect enemy attacks and instantly strike back.',
        key: 'INV_DESC_SKILL_PARRY',
      },
      silk: 4,
      attacks: [{ scale: 'needle', hits: [[[4, 4]], [[7, 4]], [[10, 4]], [[13, 4]], [[16, 4]]] }],
    },
    {
      id: 'sharpdart',
      key: 'INV_NAME_SKILL_SILKDASH',
      name: { es: 'Dardo veloz', en: 'Sharpdart', key: 'INV_NAME_SKILL_SILKDASH' },
      desc: {
        es: 'Técnica mortal de las Tejedoras. Atraviesa a los enemigos con un destello de hoja y seda.',
        en: 'Deadly Weaver technique. Pierce through enemies in a blur of blade and Silk.',
        key: 'INV_DESC_SKILL_SILKDASH',
      },
      silk: 4,
      attacks: [
        {
          scale: 'needle',
          hits: [
            [[14, 1], [1, 1], [1, 1], [1, 1]],
            [[25, 1], [2, 1], [2, 1], [2, 1]],
            [[36, 1], [3, 1], [3, 1], [3, 1]],
            [[47, 1], [4, 1], [4, 1], [4, 1]],
            [[58, 1], [5, 1], [5, 1], [5, 1]],
          ],
        },
      ],
    },
    {
      id: 'rune-rage',
      key: 'INV_NAME_SKILL_SILKBOMB',
      name: { es: 'Furia rúnica', en: 'Rune Rage', key: 'INV_NAME_SKILL_SILKBOMB' },
      desc: {
        es: 'Técnica olvidada de las Tejedoras. Cose runas desgarradoras contra los enemigos.',
        en: 'Forgotten Weaver technique. Sew rending runes upon one\'s enemies.',
        key: 'INV_DESC_SKILL_SILKBOMB',
      },
      silk: 4,
      attacks: [{ scale: 'needle', hits: [[[10, 1]], [[19, 1]], [[27, 1]], [[36, 1]], [[44, 1]]] }],
    },
    {
      id: 'pale-nails',
      key: 'INV_NAME_SKILL_SILKBOSS_NEEDLE',
      name: { es: 'Uñas pálidas', en: 'Pale Nails', key: 'INV_NAME_SKILL_SILKBOSS_NEEDLE' },
      silk: 4,
      attacks: [{ scale: 'needle', hits: [[[5, 3]], [[9, 3]], [[13, 3]], [[17, 3]], [[21, 3]]] }],
    },
  ];

  const ARTS = [
    {
      id: 'needle-strike',
      key: 'INV_NAME_SKILL_CHARGESLASH',
      name: { es: 'Golpe concentrado', en: 'Needle Strike', key: 'INV_NAME_SKILL_CHARGESLASH' },
      completion: 1,
    },
    {
      id: 'swift-step',
      key: 'INV_NAME_SKILL_SPRINT',
      name: { es: 'Paso ágil', en: 'Swift Step', key: 'INV_NAME_SKILL_SPRINT' },
      desc: {
        es: 'Técnica legendaria de las Tejedoras. Avanza y esprinta con una velocidad antinatural, como si planeases sobre la seda.',
        en: 'Fabled Weaver talent. Dash forward and sprint with unnatural speed, as though gliding upon Silk.',
        key: 'INV_DESC_SKILL_SPRINT',
      },
      completion: 1,
    },
    {
      id: 'cling-grip',
      key: 'INV_NAME_WALLJUMP',
      name: { es: 'Agarre de pinza', en: 'Cling Grip', key: 'INV_NAME_WALLJUMP' },
      desc: {
        es: 'Técnica antigua de las Tejedoras. Agárrate a superficies escarpadas y salta desde ellas para escalar con rapidez.',
        en: 'Ancient Weaver technique. Cling to sheer surfaces and leap off to rapidly scale heights.',
        key: 'INV_DESC_WALLJUMP',
      },
      completion: 1,
    },
    {
      id: 'clawline',
      key: 'INV_NAME_SKILL_HARPOON',
      name: { es: 'Garra elongada', en: 'Clawline', key: 'INV_NAME_SKILL_HARPOON' },
      desc: {
        es: 'Técnica avanzada de las Tejedoras. Lanza la aguja encordada en seda como un arpón y carga tras ella.',
        en: 'Advanced Weaver talent. Throw the Silk-strung needle like a harpoon and charge towards it.',
        key: 'INV_DESC_SKILL_HARPOON',
      },
      completion: 1,
    },
    {
      id: 'silk-soar',
      key: 'INV_NAME_SKILL_ASCENT',
      name: { es: 'Vuelo sedeño', en: 'Silk Soar', key: 'INV_NAME_SKILL_ASCENT' },
      desc: {
        es: 'Técnica antigua de las Tejedoras. Arroja la aguja hacia arriba y te lanza a gran altura.',
        en: 'Ancient Weaver talent. Throw the needle upward and launch to tremendous heights.',
        key: 'INV_DESC_SKILL_ASCENT',
      },
      completion: 1,
    },
    {
      id: 'sylphsong',
      key: 'INV_NAME_SKILL_EVAHEAL',
      name: { es: 'Silfonía', en: 'Sylphsong', key: 'INV_NAME_SKILL_EVAHEAL' },
      desc: {
        es: 'Esencia de un ser fusionado en su interior. Descansar en un banco restablece la seda.',
        en: 'Essence of a being merged within. Silk will be restored when resting at a bench.',
        key: 'INV_DESC_SKILL_EVAHEAL',
      },
      completion: 1,
    },
    {
      id: 'needolin',
      key: 'INV_NAME_SKILL_NEEDOLIN',
      name: { es: 'Agujolín', en: 'Needolin', key: 'INV_NAME_SKILL_NEEDOLIN' },
      desc: {
        es: 'Técnica sagrada de las Tejedoras. Encuerda seda a lo largo de la aguja para tocar melodías antiguas.',
        en: 'Holy Weaver talent. Play ancient melodies by stringing Silk along the needle.',
        key: 'INV_DESC_SKILL_NEEDOLIN',
      },
      completion: 1,
    },
    {
      id: 'drifters-cloak',
      key: 'INV_NAME_DRESS_BROLLY',
      name: { es: 'Capa de flotador', en: 'Drifter\'s Cloak', key: 'INV_NAME_DRESS_BROLLY' },
      desc: {
        es: 'Simple atuendo protector, cosido con púas flexibles.',
        en: 'Simple protective garb, sewn through with flexible spines.',
        key: 'INV_DESC_DRESS_BROLLY',
      },
    },
    {
      id: 'faydown-cloak',
      key: 'INV_NAME_DRESS_DJ',
      name: { es: 'Capa de fayforno', en: 'Faydown Cloak', key: 'INV_NAME_DRESS_DJ' },
      desc: {
        es: 'Atuendo protector forrado con el suave plumón de un fayforno y cosido con púas flexibles.',
        en: 'Protective garb lined with the soft down of a Fayforn and sewn through with flexible spines.',
        key: 'INV_DESC_DRESS_DJ',
      },
    },
    {
      id: 'beastling-call',
      key: 'INV_NAME_SKILL_BELLBEAST_MELODY',
      name: { es: 'Reclamo de bestezuelas', en: 'Beastling Call', key: 'INV_NAME_SKILL_BELLBEAST_MELODY' },
      desc: {
        es: 'Convoca a las bestezuelas, que luego vuelven con su madre.',
        en: 'Summon the Beastlings and return together to their mother.',
        key: 'INV_DESC_SKILL_BELLBEAST_MELODY',
      },
    },
    {
      id: 'elegy-of-the-deep',
      key: 'INV_NAME_SKILL_MEMORY_MELODY',
      name: {
        es: 'Elegía de las profundidades',
        en: 'Elegy of the Deep',
        key: 'INV_NAME_SKILL_MEMORY_MELODY',
      },
      desc: {
        es: 'Sintoniza con las viejas memorias de Telalejana.',
        en: 'Attune to the old memories of Pharloom.',
        key: 'INV_DESC_SKILL_MEMORY_MELODY',
      },
    },
  ];

  const MODIFIERS = [
    {
      to: 'needle',
      add: 0.5,
      id: 'challenge',
      from: 'BUTTON_TAUNT',
      name: { es: 'Desafiar', en: 'Challenge', key: 'BUTTON_TAUNT' },
      firstHit: true,
    },
    { to: 'needle', add: 0.3, id: 'hunter-focus-2', crest: 'hunter', stage: 2 },
    { to: 'needle', add: 0.2, id: 'hunter-focus-3', crest: 'hunter', stage: 3 },
    { to: 'needle', mul: 3, id: 'wanderer-critical', crest: 'wanderer' },
    { to: 'needle', add: 0.25, id: 'beast-fury', crest: 'beast' },
    { to: 'needle', add: 0.5, id: 'flintslate', tool: 'flintslate' },
    { to: 'needle', add: 0.25, id: 'barbed-bracelet', tool: 'barbed-bracelet' },
    { to: 'skill', add: 0.4, id: 'shaman', crest: 'shaman' },
    { to: 'skill', add: 0.25, id: 'volt-filament', tool: 'volt-filament' },
  ];

  const ITEMS = [
    {
      id: 'mask-shard',
      key: 'INV_NAME_HEART_PIECE_1',
      name: { es: 'Fragmento de máscara', en: 'Mask Shard', key: 'INV_NAME_HEART_PIECE_1' },
    },
    {
      id: 'spool-fragment',
      key: 'INV_NAME_SPOOL_PIECE_HALF',
      name: { es: 'Fragmento de carrete', en: 'Spool Fragment', key: 'INV_NAME_SPOOL_PIECE_HALF' },
    },
    {
      id: 'memory-locket',
      key: 'INV_NAME_CREST_SOCKET',
      name: { es: 'Relicario de memorias', en: 'Memory Locket', key: 'INV_NAME_CREST_SOCKET' },
    },
    {
      id: 'tool-pouch',
      key: 'INV_NAME_TOOLPOUCH',
      name: { es: 'Bolsa de herramientas', en: 'Tool Pouch', key: 'INV_NAME_TOOLPOUCH' },
    },
    {
      id: 'crafting-kit',
      key: 'INV_MSG_TOOLKIT',
      name: { es: 'Kit de fabricación', en: 'Crafting Kit', key: 'INV_MSG_TOOLKIT' },
    },
    {
      id: 'pale-oil',
      key: 'INV_NAME_PLINNEY_TOOLS',
      name: { es: 'Aceite pálido', en: 'Pale Oil', key: 'INV_NAME_PLINNEY_TOOLS' },
    },
    {
      id: 'craftmetal',
      key: 'INV_NAME_TOOL_METAL',
      name: { es: 'Metal artesano', en: 'Craftmetal', key: 'INV_NAME_TOOL_METAL' },
    },
    {
      id: 'everbloom',
      key: 'INV_NAME_WHITE_FLOWER',
      name: { es: 'Siempreviva', en: 'Everbloom', key: 'INV_NAME_WHITE_FLOWER' },
    },
    {
      id: 'farsight',
      key: 'INV_NAME_FARSIGHT',
      name: { es: 'Vistalejana', en: 'Farsight', key: 'INV_NAME_FARSIGHT' },
    },
    {
      id: 'hunters-journal',
      key: 'INV_NAME_JOURNAL',
      name: { es: 'Diario de caza', en: 'Hunter\'s Journal', key: 'INV_NAME_JOURNAL' },
    },
  ];

  const HORNET = {
    masks: { base: 5, shards: 20, perMask: 4 },
    silk: { base: 9, fragments: 18, perSpool: 2, extender: 3, bind: 9, skill: 4 },
    bind: { heals: 3, seconds: 1.37 },
    kit: { levels: 4, boost: 0.6 },
    pouch: { levels: 4 },
  };

  SS.data = { NEEDLES, CRESTS, OTHER_CRESTS, VESTICREST, TOOLS, SKILLS, ARTS, MODIFIERS, ITEMS, HORNET };
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.data;
})();
