/* js/hero.js — how fast Hornet slashes with each Crest, in seconds.
   GENERATED by tools/extract-hero.py from the game's own files (each Crest's
   HeroControllerConfig): not edited by hand. SLASH: by the Crest's name as the save names it
   (js/collectibles.js CRESTS), its attackDuration, attackCooldownTime and
   quickAttackCooldownTime (Flea Brew's), and the Beast's in fury (rage). A slash waits
   max(cooldown, duration) after the one before (js/engine.js). QUICKENING: how long Flea
   Brew's lasts. REGEN: Silk Hearts' regeneration, a strand after delay + duration seconds
   (first*: from an empty spool) while the silk is below the cap and doesn't change;
   weavelight: its time multiplier and what it adds to the cap. COMBAT: what a fight runs on
   (js/fight.js): the Needle Strike's charge, the Hunter's focus as [needle hits, ×damage],
   the Beast's fury and the Reaper's mode in seconds. */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});
  SS.hero = {
    "SLASH": {
      "Cloakless": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.41,
        "quickAttackCooldownTime": 0.205
      },
      "Cursed": {
        "attackDuration": 0.4,
        "attackCooldownTime": 0.45,
        "quickAttackCooldownTime": 0.2375
      },
      "Hunter": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.41,
        "quickAttackCooldownTime": 0.205
      },
      "Hunter_v2": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.41,
        "quickAttackCooldownTime": 0.205
      },
      "Hunter_v3": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.41,
        "quickAttackCooldownTime": 0.205
      },
      "Reaper": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.5,
        "quickAttackCooldownTime": 0.25
      },
      "Spell": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.5,
        "quickAttackCooldownTime": 0.25
      },
      "Toolmaster": {
        "attackDuration": 0.35,
        "attackCooldownTime": 0.45,
        "quickAttackCooldownTime": 0.225
      },
      "Wanderer": {
        "attackDuration": 0.25,
        "attackCooldownTime": 0.3,
        "quickAttackCooldownTime": 0.15
      },
      "Warrior": {
        "attackDuration": 0.3,
        "attackCooldownTime": 0.39,
        "quickAttackCooldownTime": 0.195,
        "rage": {
          "attackDuration": 0.3,
          "attackCooldownTime": 0.32,
          "quickAttackCooldownTime": 0.195
        }
      },
      "Witch": {
        "attackDuration": 0.4,
        "attackCooldownTime": 0.45,
        "quickAttackCooldownTime": 0.2375
      }
    },
    "QUICKENING": 10.0,
    "REGEN": {
      "firstDelay": 0.65,
      "firstDuration": 0.8,
      "delay": 2.0,
      "duration": 1.9,
      "weavelight": {
        "time": 0.65,
        "cap": 1
      }
    },
    "COMBAT": {
      "charge": 1.35,
      "chargeQuick": 0.8,
      "invul": 1.0,
      "hunter": [
        [
          6,
          1.3
        ],
        [
          12,
          1.5
        ]
      ],
      "fury": {
        "secs": 5.0,
        "hurt": 2.5,
        "mult": 1.25
      },
      "reaper": 10.0
    }
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.hero;
})();
