/* js/how.js: how to get each thing of the 100%, as data (no prose): its ways, best first.
   GENERATED by tools/gen-how.js from js/shop.js (the game's shops and wish rewards), the save's
   checks (js/collectibles.js PIECES), the wiki's boss drops (js/enemies.js BOSSES) and wish
   rewards (kb/data/raw/Wishes.wiki), and a short table by hand (the generator's HAND): not
   edited by hand. Change the generator and run npm run data.

     NPCS    npc id → the game's name (the vendors and the NPCs who give things)
     HOW     { tools, crests, skills, arts: { site id: [way…] }, pieces: { PIECES index: [way…] },
             everbloom: [way…] }. The Tools by their COUNTED group's first id; the pieces those
             that count (Mask Shards, Spool Fragments, Crafting Kit, Tool Pouch, Needle, Silk
             Hearts). A way is one of:
               { kind: 'shop', vendor, price, item, craftmetal?, paleOil?, act?, after?, needs? }
                 price in rosaries; item the ShopItem in js/shop.js SHOP (Plinney's Needle: its
                 cost's name); craftmetal, paleOil what it also takes; act 3 sold only then;
                 after the WISHES indices to be done first; needs the playerData flags it waits on
               { kind: 'wish', wish, quest, act? }  wish a WISHES index, quest its save name
               { kind: 'boss', foe }  a js/enemies.js FOES id
               { kind: 'found', act? }  lying in a room (from that Act on)
               { kind: 'craft', craftmetal }  made at a craft table
               { kind: 'npc', npc }  given for nothing
               { kind: 'challenge', npc }  won from the NPC
               { kind: 'fleas', npc, fleas }  Mooshka's, for that many Lost Fleas ('all')
     TRAPS   the ways to lose a point or a wish: curveclaw (lost: the save names hidden and
             locked while it's gone; back: how it returns), silkshot (variants: the save's name
             and way of each; the first repaired locks the others), broodfeast-runt (the wish
             done as counts or as instead: only counts is Act 3's) */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});

  const NPCS = {
    grindle: { es: 'Grindle', en: 'Grindle', key: 'GRINDLE_MAIN' },
    pebb: { es: 'Pebb', en: 'Pebb', key: 'BB_SHOPKEEP_MAIN' },
    frey: { es: 'Frey', en: 'Frey', key: 'BELLHART_SHOPKEEP_MAIN' },
    mort: { es: 'Mort', en: 'Mort', key: 'PILGRIM_REST_SHOP_MAIN' },
    'twelfth-architect': { es: 'Duodécimo Arquitecto', en: 'Twelfth Architect', key: 'ARCHITECT_SHOP_TITLE' },
    jubilana: { es: 'Jubilana', en: 'Jubilana', key: 'CITY_MERCHANT_MAIN' },
    shakra: { es: 'Shakra', en: 'Shakra', key: 'MAPPER_MAIN' },
    plinney: { es: 'Plinney', en: 'Plinney', key: 'PINSMITH_MAIN' },
    eva: { es: 'Eva', en: 'Eva', key: 'CREST_UPG_SHRINE_MAIN' },
    pinstress: { es: 'Alfilera', en: 'Pinstress', key: 'PINSTRESS_MAIN' },
    loddie: { es: 'Loddie', en: 'Loddie', key: 'LADYBUG_LARGE_MAIN' },
    lumble: { es: 'Lumble', en: 'Lumble', key: 'DICE_PILGRIM_MAIN' },
    mooshka: { es: 'Mooshka', en: 'Mooshka', key: 'FLEAMASTER_MAIN' },
    'forge-daughter': { es: 'Forge Daughter', en: 'Forge Daughter' },
    'mottled-skarr': { es: 'Mottled Skarr', en: 'Mottled Skarr' },
  };

  const HOW = {
    tools: {
      'straight-pin': [{ kind: 'found' }],
      'threefold-pin': [{ kind: 'found' }],
      'sting-shard': [
        {
          kind: 'shop',
          vendor: 'forge-daughter',
          price: 140,
          item: 'Forge Sting Shard Tool',
          craftmetal: 1,
        },
      ],
      tacks: [{ kind: 'wish', wish: 53, quest: 'Roach Killing' }, { kind: 'found', act: 3 }],
      longpin: [{ kind: 'found' }],
      curveclaw: [
        { kind: 'shop', vendor: 'mottled-skarr', price: 140, item: 'Ant Merchant Curve Claws Tool' },
        { kind: 'found', act: 2 },
      ],
      'throwing-ring': [{ kind: 'wish', wish: 29, quest: 'Shakra Final Quest' }],
      pimpillo: [{ kind: 'craft', craftmetal: 1 }],
      conchcutter: [{ kind: 'boss', foe: 'raging-conchfly' }],
      silkshot: [
        {
          kind: 'shop',
          vendor: 'forge-daughter',
          price: 240,
          item: 'Forge SilkShot',
          craftmetal: 1,
          needs: ['ForgeDaughterMentionedWebShot'],
        },
        {
          kind: 'shop',
          vendor: 'twelfth-architect',
          price: 130,
          item: 'Architect SilkShot',
          craftmetal: 1,
          needs: ['ArchitectMentionedWebShot'],
        },
        { kind: 'craft', craftmetal: 1 },
      ],
      'delvers-drill': [{ kind: 'found' }],
      'cogwork-wheel': [
        {
          kind: 'shop',
          vendor: 'twelfth-architect',
          price: 360,
          item: 'Architect Cogwork Saw',
          craftmetal: 1,
        },
      ],
      cogfly: [{ kind: 'craft', craftmetal: 1 }],
      'rosary-cannon': [{ kind: 'found' }],
      voltvessels: [{ kind: 'found' }],
      flintslate: [{ kind: 'found' }],
      'flea-brew': [{ kind: 'wish', wish: 21, quest: 'Save the Fleas' }],
      'plasmium-phial': [{ kind: 'wish', wish: 39, quest: 'Extractor Blue' }],
      'druids-eye': [{ kind: 'wish', wish: 36, quest: 'Mossberry Collection 1' }],
      'magma-bell': [
        {
          kind: 'shop',
          vendor: 'forge-daughter',
          price: 110,
          item: 'Forge Lava Charm Tool',
          craftmetal: 1,
        },
      ],
      'warding-bell': [{ kind: 'found' }],
      'pollip-pouch': [{ kind: 'wish', wish: 37, quest: 'Shell Flowers' }],
      'fractured-mask': [
        {
          kind: 'shop',
          vendor: 'mottled-skarr',
          price: 260,
          item: 'Ant Merchant Fractured Mask Tool',
        },
        { kind: 'found', act: 2 },
      ],
      multibinder: [{ kind: 'shop', vendor: 'frey', price: 880, item: 'Bellhart Multibind', after: [22] }],
      weavelight: [{ kind: 'boss', foe: 'moss-mother-weavenest-atla' }],
      'sawtooth-circlet': [
        {
          kind: 'shop',
          vendor: 'twelfth-architect',
          price: 230,
          item: 'Architect Brolly Spike',
          craftmetal: 1,
          needs: ['hasBrolly'],
        },
      ],
      'injector-band': [{ kind: 'found' }],
      'spool-extender': [{ kind: 'shop', vendor: 'jubilana', price: 720, item: 'City Merchant Spool Extender' }],
      'reserve-bind': [{ kind: 'wish', wish: 31, quest: 'Song Knight' }],
      'claw-mirror': [{ kind: 'boss', foe: 'trobbio' }],
      'memory-crystal': [{ kind: 'found' }],
      'snitch-pick': [
        {
          kind: 'shop',
          vendor: 'grindle',
          price: 740,
          item: 'Grindle Thief Claw',
          needs: ['hasHarpoonDash'],
        },
      ],
      'volt-filament': [{ kind: 'boss', foe: 'voltvyrm' }],
      'quick-sling': [{ kind: 'found' }],
      'wreath-of-purity': [{ kind: 'found' }],
      longclaw: [
        { kind: 'wish', wish: 56, quest: 'Huntress Quest' },
        { kind: 'wish', wish: 56, quest: 'Huntress Quest Runt', act: 3 },
      ],
      'wispfire-lantern': [{ kind: 'boss', foe: 'father-of-the-flame' }],
      'egg-of-flealia': [{ kind: 'fleas', npc: 'mooshka', fleas: 'all' }],
      'pin-badge': [{ kind: 'wish', wish: 32, quest: 'Pinstress Battle' }],
      compass: [{ kind: 'shop', vendor: 'shakra', price: 70, item: 'Mapper Compass Tool' }],
      'shard-pendant': [{ kind: 'found' }],
      'magnetite-brooch': [
        { kind: 'shop', vendor: 'pebb', price: 120, item: 'Bonebottom Rosary Magnet Tool' },
        { kind: 'shop', vendor: 'grindle', price: 220, item: 'Grindle Rosary Magnet', act: 3 },
      ],
      'weighted-belt': [
        { kind: 'shop', vendor: 'mort', price: 160, item: 'Pilgrims Rest Weighted Anklet Tool' },
        { kind: 'found', act: 3 },
      ],
      'barbed-bracelet': [{ kind: 'found' }],
      'dead-bugs-purse': [{ kind: 'found' }],
      'magnetite-dice': [
        { kind: 'challenge', npc: 'lumble' },
        { kind: 'found', act: 2 },
        { kind: 'shop', vendor: 'grindle', price: 300, item: 'Grindle Lucky Dice Tool', act: 3 },
      ],
      scuttlebrace: [
        {
          kind: 'shop',
          vendor: 'twelfth-architect',
          price: 140,
          item: 'Architect Scuttlebrace',
          craftmetal: 1,
        },
      ],
      'ascendants-grip': [{ kind: 'shop', vendor: 'jubilana', price: 350, item: 'City Merchant Wallcling Tool' }],
      'spider-strings': [
        {
          kind: 'shop',
          vendor: 'jubilana',
          price: 320,
          item: 'City Merchant Needolin Tool',
          after: [30],
        },
      ],
      'silkspeed-anklets': [{ kind: 'found' }],
      'thiefs-mark': [{ kind: 'shop', vendor: 'grindle', price: 350, item: 'Grindle Thief Charm' }],
    },
    crests: {
      reaper: [{ kind: 'found' }],
      wanderer: [{ kind: 'found' }],
      beast: [{ kind: 'boss', foe: 'savage-beastfly-chapel-of-the-beast' }],
      witch: [{ kind: 'wish', wish: 27, quest: 'Doctor Curse Cure' }],
      architect: [{ kind: 'found' }],
      shaman: [{ kind: 'found' }],
    },
    skills: {
      silkspear: [{ kind: 'found' }],
      'thread-storm': [{ kind: 'found' }],
      'cross-stitch': [{ kind: 'boss', foe: 'phantom' }],
      sharpdart: [{ kind: 'found' }],
      'rune-rage': [{ kind: 'boss', foe: 'first-sinner' }],
      'pale-nails': [{ kind: 'found' }],
    },
    arts: {
      needolin: [{ kind: 'boss', foe: 'widow' }],
      'swift-step': [{ kind: 'found' }],
      'cling-grip': [{ kind: 'boss', foe: 'sister-splinter' }],
      clawline: [{ kind: 'found' }],
      'silk-soar': [{ kind: 'found' }],
      sylphsong: [{ kind: 'npc', npc: 'eva' }],
      'needle-strike': [{ kind: 'npc', npc: 'pinstress' }],
    },
    pieces: {
      '0': [
        { kind: 'shop', vendor: 'pebb', price: 300, item: 'Bonebottom Mask Shard' },
        { kind: 'shop', vendor: 'grindle', price: 320, item: 'Grindle Mask Shard', act: 3 },
      ],
      '1': [{ kind: 'found' }],
      '2': [{ kind: 'found' }],
      '3': [{ kind: 'found' }],
      '4': [{ kind: 'found' }],
      '5': [{ kind: 'found' }],
      '6': [{ kind: 'wish', wish: 58, quest: 'Beastfly Hunt' }],
      '7': [{ kind: 'found' }],
      '8': [{ kind: 'found' }],
      '9': [{ kind: 'found' }],
      '10': [{ kind: 'found' }],
      '11': [{ kind: 'found' }],
      '12': [{ kind: 'found' }],
      '13': [{ kind: 'found' }],
      '14': [{ kind: 'shop', vendor: 'jubilana', price: 750, item: 'City Merchant Heart Piece' }],
      '15': [{ kind: 'found' }],
      '16': [{ kind: 'wish', wish: 71, quest: 'Sprintmaster Race' }],
      '17': [{ kind: 'wish', wish: 61, quest: 'Ant Trapper' }],
      '18': [{ kind: 'wish', wish: 60, quest: 'Destroy Thread Cores' }],
      '19': [{ kind: 'found' }],
      '20': [{ kind: 'found' }],
      '21': [{ kind: 'found' }],
      '22': [{ kind: 'found' }],
      '23': [{ kind: 'found' }],
      '24': [{ kind: 'found' }],
      '25': [{ kind: 'shop', vendor: 'frey', price: 270, item: 'Belltown Spool Segment', after: [22] }],
      '26': [{ kind: 'fleas', npc: 'mooshka', fleas: 14 }],
      '27': [{ kind: 'found' }],
      '28': [{ kind: 'found' }],
      '29': [{ kind: 'found' }],
      '30': [{ kind: 'found' }],
      '31': [{ kind: 'found' }],
      '32': [{ kind: 'wish', wish: 28, quest: 'Save Sherma' }],
      '33': [{ kind: 'found' }],
      '34': [{ kind: 'found' }],
      '35': [{ kind: 'found' }],
      '36': [{ kind: 'shop', vendor: 'grindle', price: 680, item: 'Grindle Spool Piece' }],
      '37': [
        {
          kind: 'shop',
          vendor: 'jubilana',
          price: 500,
          item: 'City Merchant Spool Piece',
          after: [30],
        },
      ],
      '99': [{ kind: 'npc', npc: 'plinney' }],
      '100': [{ kind: 'shop', vendor: 'plinney', price: 0, item: 'Nail Upgrade', paleOil: 1 }],
      '101': [
        {
          kind: 'shop',
          vendor: 'plinney',
          price: 450,
          item: 'Nail Upgrade Further Cost',
          paleOil: 1,
        },
      ],
      '102': [{ kind: 'shop', vendor: 'plinney', price: 680, item: 'Nail Upgrade Final Cost', paleOil: 1 }],
      '103': [
        { kind: 'shop', vendor: 'mort', price: 220, item: 'Pilgrims Rest Tool Pouch' },
        { kind: 'shop', vendor: 'grindle', price: 220, item: 'Grindle Tool Pouch', act: 3 },
      ],
      '104': [{ kind: 'challenge', npc: 'loddie' }, { kind: 'found', act: 3 }],
      '105': [{ kind: 'wish', wish: 69, quest: 'Journal' }],
      '106': [{ kind: 'fleas', npc: 'mooshka', fleas: 20 }],
      '107': [{ kind: 'shop', vendor: 'forge-daughter', price: 180, item: 'Forge Tool Kit' }],
      '108': [{ kind: 'wish', wish: 51, quest: 'Crow Feathers' }],
      '109': [{ kind: 'shop', vendor: 'grindle', price: 700, item: 'Grindle Tool Kit' }],
      '110': [{ kind: 'shop', vendor: 'twelfth-architect', price: 450, item: 'Architect Tool Kit' }],
      '111': [{ kind: 'boss', foe: 'bell-beast' }],
      '112': [{ kind: 'boss', foe: 'the-unravelled' }],
      '113': [{ kind: 'boss', foe: 'lace-the-cradle' }],
    },
    everbloom: [{ kind: 'wish', wish: 16, quest: 'Black Thread Pt5 Heart' }],
  };

  const TRAPS = [
    {
      id: 'curveclaw',
      thing: ['tools', 'curveclaw'],
      act: 3,
      lost: { hidden: 'Curve Claws', locked: 'Curve Claws Upgraded' },
      back: { tool: 'curvesickle', way: { kind: 'found', act: 3 } },
    },
    {
      id: 'silkshot',
      thing: ['tools', 'silkshot'],
      variants: [
        {
          save: 'WebShot Forge',
          way: {
            kind: 'shop',
            vendor: 'forge-daughter',
            price: 240,
            item: 'Forge SilkShot',
            craftmetal: 1,
            needs: ['ForgeDaughterMentionedWebShot'],
          },
        },
        {
          save: 'WebShot Architect',
          way: {
            kind: 'shop',
            vendor: 'twelfth-architect',
            price: 130,
            item: 'Architect SilkShot',
            craftmetal: 1,
            needs: ['ArchitectMentionedWebShot'],
          },
        },
        { save: 'WebShot Weaver', way: { kind: 'craft', craftmetal: 1 } },
      ],
    },
    {
      id: 'broodfeast-runt',
      thing: ['tools', 'longclaw'],
      wish: 56,
      counts: 'Huntress Quest',
      instead: 'Huntress Quest Runt',
    },
  ];

  SS.how = { NPCS, HOW, TRAPS };
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.how;
})();
