/* js/phases.js — each boss's phases: where its FSM moves on (at: highest first, a number below
   1 a share of its health, from 1 up a health) and, when each phase has a health of its own,
   its bars. By the boss's id in js/enemies.js.
   GENERATED by tools/extract-phases.py from the game's own files: not edited by hand. */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});
  SS.phases = {"bell-beast":{"at":[0.8,0.5]},"broodmother":{"at":[0.55]},"clover-dancers":{"bars":[580,580]},"cogwork-dancers":{"bars":[190,220,220,180]},"crust-king-khann":{"at":[0.75,0.4]},"fourth-chorus":{"at":[451,326,201]},"grand-mother-silk":{"bars":[100,192,240,110,242,340]},"lace":{"at":[0.5]},"lace-the-cradle":{"at":[0.75,0.4]},"last-judge":{"at":[0.75,0.3]},"lost-lace":{"at":[0.5]},"moorwing":{"at":[0.65]},"nyleth":{"at":[0.7]},"palestag":{"at":[0.45]},"pinstress":{"at":[0.85]},"plasmified-zango":{"at":[0.95,0.75,0.5,0.25]},"savage-beastfly-chapel-of-the-beast":{"at":[0.45]},"savage-beastfly-far-fields":{"at":[0.45]},"shrine-guardian-seth":{"at":[0.75,0.4]},"summoned-saviour":{"at":[0.8,0.4]},"the-unravelled":{"at":[0.8,0.4]},"voltvyrm":{"at":[0.9,0.5]},"widow":{"at":[0.7,150]}};
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.phases;
})();
