/* js/phases.js — each boss's phases: where its FSM moves on (at: highest first, a number below
   1 a share of its health, from 1 up a health) and, when each phase has a health of its own,
   its bars. By the boss's id in js/enemies.js. And, for the few that go otherwise:
     of      the health the shares are of, when it's one of the fight's bars (Signis's)
     pieces  how many pieces make each bar, each breaking at its share or after its `hits`
             (Father of the Flame's four lanterns, then its core)
     heal    [at, add, max]: when one of two falls, the other at `at` or below heals `add`,
             to `max` at most (the Forebrothers)
     reset   at 0, the health it's set back to if the finishing prompt is missed (Phantom's)
   GENERATED by tools/extract-phases.py from the game's own files: not edited by hand. */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});
  SS.phases = {"bell-beast":{"at":[0.8,0.5]},"bell-eater":{"at":[0.75,0.4]},"broodmother":{"at":[0.55]},"clover-dancers":{"bars":[580,580]},"cogwork-dancers":{"bars":[190,220,220,180]},"crawfather":{"at":[0.6]},"crust-king-khann":{"at":[0.75,0.4]},"disgraced-chef-lugoli":{"at":[0.5]},"father-of-the-flame":{"bars":[400,250],"pieces":[4,1],"hits":[12,30]},"first-sinner":{"at":[0.5]},"forebrothers-signis-and-gron":{"heal":[350,200,350],"at":[0.9,0.7,0.5],"of":720},"fourth-chorus":{"at":[451,326,201]},"grand-mother-silk":{"bars":[100,192,240,110,242,340]},"groal-the-great":{"at":[0.6]},"gurr-the-outcast":{"at":[0.6,0.4]},"lace":{"at":[0.5]},"lace-the-cradle":{"at":[0.75,0.4]},"last-judge":{"at":[0.75,0.3]},"lost-lace":{"at":[0.75,0.5,0.3]},"moorwing":{"at":[0.65]},"moss-mother-act-3-moss-grotto":{"at":[0.95]},"moss-mother-ruined-chapel":{"at":[0.95]},"moss-mother-weavenest-atla":{"at":[0.95]},"nyleth":{"at":[0.7]},"palestag":{"at":[0.45]},"phantom":{"at":[0.35],"reset":60},"pinstress":{"at":[0.85]},"plasmified-zango":{"at":[0.95,0.75,0.5,0.25]},"raging-conchfly":{"at":[0.7]},"savage-beastfly-chapel-of-the-beast":{"at":[0.8,0.45]},"savage-beastfly-far-fields":{"at":[0.8,0.45]},"second-sentinel":{"at":[0.5]},"shrine-guardian-seth":{"at":[0.75,0.4]},"sister-splinter":{"at":[0.8,0.4]},"skarrsinger-karmelita":{"at":[0.65,0.35]},"summoned-saviour":{"at":[0.8,0.4]},"the-unravelled":{"at":[0.8,0.4]},"tormented-trobbio":{"at":[0.5]},"trobbio":{"at":[0.5]},"voltvyrm":{"at":[0.9,0.5]},"widow":{"at":[0.7,150]}};
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.phases;
})();
