/* js/shop.js: what each vendor sells and for how much, and what each wish gives, from the
   game's own files (patch 1.0.30000). GENERATED by tools/extract-shops.py: not edited by hand.
     VENDORS  vendor id → the scenes it sells in (its names: js/how.js NPCS)
     SHOP     every item a vendor sells: item (the game's ShopItem), vendor, what it gives (tool:
              a site Tool id; piece: an index of js/collectibles.js PIECES; thing: anything
              else, by the game's name), name (its text key), price (rosaries), craftmetal (how
              many it also takes), act 3 (only then), needs (playerData flags for it to show),
              after (wishes, by save name, to be done first), flag (what buying it sets)
     REWARDS  wish (save name) → what completing it gives, when the wish itself gives it
              (the same shapes, and count); the rewards an NPC hands over aren't here
     NEEDLE   Plinney's two paid upgrades, in rosaries (costs.bundle)
     UNSOLD   ShopItems in no vendor's stock: in the files, not in the game */
(() => {
  'use strict';
  const SS = globalThis.SS || (globalThis.SS = {});

  const VENDORS = {
    "forge-daughter": ["room_forge"],
    "frey": ["belltown"],
    "grindle": ["coral_42"],
    "jubilana": ["hang_04", "library_03", "song_enclave"],
    "mort": ["bone_east_10_room"],
    "mottled-skarr": ["ant_merchant"],
    "pebb": ["bonetown"],
    "shakra": ["ant_04_mid", "ant_20", "belltown", "bone_04", "bone_east_01", "bone_east_21", "bonetown", "coral_12", "coral_40", "crawl_01", "dust_10", "greymoor_02", "greymoor_08", "peak_02", "shadow_23", "shellwood_01", "shellwood_16"],
    "twelfth-architect": ["under_17"],
  };

  const SHOP = [
    {"item": "Forge Lava Charm Tool", "vendor": "forge-daughter", "tool": "magma-bell", "name": "LAVA_CHARM_NAME", "price": 110, "craftmetal": 1},
    {"item": "Forge Shard Pouch", "vendor": "forge-daughter", "thing": "Shard Pouch", "name": "INV_NAME_SHARD_POUCH", "price": 50},
    {"item": "Forge SilkShot", "vendor": "forge-daughter", "tool": "silkshot", "name": "SILKSHOT_NAME", "price": 240, "craftmetal": 1, "needs": ["ForgeDaughterMentionedWebShot"]},
    {"item": "Forge Sting Shard Tool", "vendor": "forge-daughter", "tool": "sting-shard", "name": "STING_SHARD_NAME", "price": 140, "craftmetal": 1},
    {"item": "Forge Tool Kit", "vendor": "forge-daughter", "piece": 107, "name": "INV_MSG_TOOLKIT", "price": 180, "flag": "PurchasedForgeToolKit"},
    {"item": "Bellhart Crest Socket", "vendor": "frey", "piece": 42, "name": "INV_NAME_CREST_SOCKET", "price": 330, "flag": "PurchasedBelltownMemoryLocket"},
    {"item": "Bellhart Furnishing Desk", "vendor": "frey", "thing": "BelltownFurnishingDesk", "name": "SHOP_ITEM_FURNISHING_DESK_NAME", "price": 380, "needs": ["BelltownHouseVisited", "IsAnyRelicsDeposited"], "flag": "BelltownFurnishingDesk"},
    {"item": "Bellhart Furnishing Gramaphone", "vendor": "frey", "thing": "BelltownFurnishingGramaphone", "name": "SHOP_ITEM_FURNISHING_GRAMAPHONE_NAME", "price": 490, "needs": ["BelltownHouseVisited", "LibrarianCollectionComplete", "BelltownFurnishingDesk"], "flag": "BelltownFurnishingGramaphone"},
    {"item": "Bellhart Furnishing Lights", "vendor": "frey", "thing": "BelltownFurnishingFairyLights", "name": "SHOP_ITEM_FURNISHING_LIGHTS_NAME", "price": 320, "needs": ["BelltownHouseVisited"], "flag": "BelltownFurnishingFairyLights"},
    {"item": "Bellhart Furnishing Paint", "vendor": "frey", "thing": "BelltownHouseColour", "name": "SHOP_ITEM_FURNISHING_PAINT_NAME", "price": 520, "needs": ["BelltownHouseVisited"]},
    {"item": "Bellhart Furnishing Spa", "vendor": "frey", "thing": "BelltownFurnishingSpa", "name": "SHOP_ITEM_FURNISHING_SPA_NAME", "price": 1100, "needs": ["BelltownHouseVisited", "BelltownFurnishingSpaAvailable"], "flag": "BelltownFurnishingSpa"},
    {"item": "Bellhart Multibind", "vendor": "frey", "tool": "multibinder", "name": "MULTIBIND_NAME", "price": 880, "after": ["Save Courier Short"]},
    {"item": "Belltown Rosary String Medium", "vendor": "frey", "thing": "Rosary_Set_Medium", "name": "INV_NAME_COIN_SET_M", "price": 140},
    {"item": "Belltown Shard Pouch", "vendor": "frey", "thing": "Shard Pouch", "name": "INV_NAME_SHARD_POUCH", "price": 50, "after": ["Save Courier Short"]},
    {"item": "Belltown Spool Segment", "vendor": "frey", "piece": 25, "name": "SHOP_SPOOL_SEGMENT_NAME", "price": 270, "after": ["Save Courier Short"], "flag": "PurchasedBelltownSpoolSegment"},
    {"item": "Grindle Crest Socket", "vendor": "grindle", "piece": 38, "name": "INV_NAME_CREST_SOCKET", "price": 250, "act": 3, "flag": "PurchasedPilgrimsRestMemoryLocket"},
    {"item": "Grindle Lucky Dice Tool", "vendor": "grindle", "tool": "magnetite-dice", "name": "MAGNETITE_DICE_NAME", "price": 300, "act": 3},
    {"item": "Grindle Mask Shard", "vendor": "grindle", "piece": 0, "name": "SHOP_SHELLFRAG_NAME", "price": 320, "act": 3, "flag": "PurchasedBonebottomHeartPiece"},
    {"item": "Grindle Psalm Cylinder", "vendor": "grindle", "thing": "Psalm Cylinder Grindle", "name": "INV_NAME_R_PSALM_CYL", "price": 240},
    {"item": "Grindle Rosary Magnet", "vendor": "grindle", "tool": "magnetite-brooch", "name": "ROSARY_MAGNET_NAME", "price": 220, "act": 3},
    {"item": "Grindle Rosary String", "vendor": "grindle", "thing": "Rosary_Set_Small", "name": "INV_NAME_COIN_SET_S", "price": 80},
    {"item": "Grindle Simple Key", "vendor": "grindle", "thing": "Simple Key", "name": "INV_NAME_TOKEN_FAITH", "price": 600, "act": 3, "flag": "PurchasedBonebottomFaithToken"},
    {"item": "Grindle Spool Piece", "vendor": "grindle", "piece": 36, "name": "SHOP_SPOOL_SEGMENT_NAME", "price": 680, "flag": "purchasedGrindleSpoolPiece"},
    {"item": "Grindle Thief Charm", "vendor": "grindle", "tool": "thiefs-mark", "name": "THIEF_CHARM_NAME", "price": 350},
    {"item": "Grindle Thief Claw", "vendor": "grindle", "tool": "snitch-pick", "name": "THIEF_CLAW_NAME", "price": 740, "needs": ["hasHarpoonDash"]},
    {"item": "Grindle Tool Kit", "vendor": "grindle", "piece": 109, "name": "INV_MSG_TOOLKIT", "price": 700, "flag": "purchasedGrindleToolKit"},
    {"item": "Grindle Tool Metal", "vendor": "grindle", "piece": 58, "name": "INV_NAME_TOOL_METAL", "price": 120, "act": 3, "flag": "PurchasedBonebottomToolMetal"},
    {"item": "Grindle Tool Pouch", "vendor": "grindle", "piece": 103, "name": "INV_NAME_TOOLPOUCH", "price": 220, "act": 3, "flag": "PurchasedPilgrimsRestToolPouch"},
    {"item": "City Merchant Heart Piece", "vendor": "jubilana", "piece": 14, "name": "SHOP_SHELLFRAG_NAME", "price": 750, "flag": "MerchantEnclaveShellFragment"},
    {"item": "City Merchant Needolin Tool", "vendor": "jubilana", "tool": "spider-strings", "name": "MUSICIAN_CHARM_NAME", "price": 320, "after": ["Save City Merchant Bridge"]},
    {"item": "City Merchant Rosary String", "vendor": "jubilana", "thing": "Rosary_Set_Small", "name": "INV_NAME_COIN_SET_S", "price": 80},
    {"item": "City Merchant Seal Chit", "vendor": "jubilana", "thing": "Seal Chit City Merchant", "name": "INV_NAME_R_SEAL_CHIT", "price": 180, "after": ["Save City Merchant Bridge"]},
    {"item": "City Merchant Simple Key", "vendor": "jubilana", "thing": "Simple Key", "name": "INV_NAME_TOKEN_FAITH", "price": 650, "flag": "MerchantEnclaveSimpleKey"},
    {"item": "City Merchant Spool Extender", "vendor": "jubilana", "tool": "spool-extender", "name": "SPOOL_EXTENDER_NAME", "price": 720},
    {"item": "City Merchant Spool Piece", "vendor": "jubilana", "piece": 37, "name": "SHOP_SPOOL_SEGMENT_NAME", "price": 500, "after": ["Save City Merchant Bridge"], "flag": "MerchantEnclaveSpoolPiece"},
    {"item": "City Merchant Tool Metal", "vendor": "jubilana", "piece": 65, "name": "INV_NAME_TOOL_METAL", "price": 180, "after": ["Save City Merchant Bridge"], "flag": "MerchantEnclaveToolMetal"},
    {"item": "City Merchant Wallcling Tool", "vendor": "jubilana", "tool": "ascendants-grip", "name": "WALLCLING_NAME", "price": 350},
    {"item": "City Merchant Ward Key", "vendor": "jubilana", "thing": "Ward Key", "name": "INV_NAME_WARD_KEY", "price": 220, "flag": "MerchantEnclaveWardKey"},
    {"item": "Pilgrims Rest Crest Socket Unlocker", "vendor": "mort", "piece": 38, "name": "INV_NAME_CREST_SOCKET", "price": 150, "flag": "PurchasedPilgrimsRestMemoryLocket"},
    {"item": "Pilgrims Rest Rosary String Small", "vendor": "mort", "thing": "Rosary_Set_Small", "name": "INV_NAME_COIN_SET_S", "price": 80},
    {"item": "Pilgrims Rest Shard Pouch", "vendor": "mort", "thing": "Shard Pouch", "name": "INV_NAME_SHARD_POUCH", "price": 50, "after": ["Courier Delivery Pilgrims Rest"]},
    {"item": "Pilgrims Rest Tool Pouch", "vendor": "mort", "piece": 103, "name": "INV_NAME_TOOLPOUCH", "price": 220, "flag": "PurchasedPilgrimsRestToolPouch"},
    {"item": "Pilgrims Rest Weighted Anklet Tool", "vendor": "mort", "tool": "weighted-belt", "name": "WEIGHTED_ANKLET_NAME", "price": 160},
    {"item": "Ant Merchant Curve Claws Tool", "vendor": "mottled-skarr", "tool": "curveclaw", "name": "CURVE_CLAWS_NAME", "price": 140},
    {"item": "Ant Merchant Fractured Mask Tool", "vendor": "mottled-skarr", "tool": "fractured-mask", "name": "FRACTURED_MASK_NAME", "price": 260},
    {"item": "Ant Merchant Shard Pouch", "vendor": "mottled-skarr", "thing": "Shard Pouch", "name": "INV_NAME_SHARD_POUCH", "price": 50},
    {"item": "Bonebottom Faith Token", "vendor": "pebb", "thing": "Simple Key", "name": "INV_NAME_TOKEN_FAITH", "price": 500, "flag": "PurchasedBonebottomFaithToken"},
    {"item": "Bonebottom Mask Shard", "vendor": "pebb", "piece": 0, "name": "SHOP_SHELLFRAG_NAME", "price": 300, "flag": "PurchasedBonebottomHeartPiece"},
    {"item": "Bonebottom Rosary Magnet Tool", "vendor": "pebb", "tool": "magnetite-brooch", "name": "ROSARY_MAGNET_NAME", "price": 120},
    {"item": "Bonebottom Rosary Set", "vendor": "pebb", "thing": "Rosary_Set_Small", "name": "INV_NAME_COIN_SET_S", "price": 80},
    {"item": "Bonebottom Tool Metal", "vendor": "pebb", "piece": 58, "name": "INV_NAME_TOOL_METAL", "price": 60, "flag": "PurchasedBonebottomToolMetal"},
    {"item": "Mapper Bellhart Map", "vendor": "shakra", "thing": "HasBellhartMap", "name": "MAPPER_ITEM_MAP_BELLHART_NAME", "price": 40, "needs": ["visitedBellhart", "visitedBellhartSaved"], "flag": "HasBellhartMap"},
    {"item": "Mapper Bellway Map Pin", "vendor": "shakra", "thing": "hasPinStag", "name": "MAPPER_ITEM_PIN_BELLWAY_NAME", "price": 60, "needs": ["defeatedBellBeast"], "flag": "hasPinStag"},
    {"item": "Mapper Bench Map Pin", "vendor": "shakra", "thing": "hasPinBench", "name": "MAPPER_ITEM_PIN_BENCH_NAME", "price": 60, "flag": "hasPinBench"},
    {"item": "Mapper Boneforest Map", "vendor": "shakra", "thing": "HasBoneforestMap", "name": "MAPPER_ITEM_MAP_BONEFOREST_NAME", "price": 50, "flag": "HasBoneforestMap"},
    {"item": "Mapper Compass Tool", "vendor": "shakra", "tool": "compass", "name": "COMPASS_NAME", "price": 70},
    {"item": "Mapper Coral Caverns Map", "vendor": "shakra", "thing": "HasCoralMap", "name": "MAPPER_ITEM_MAP_CORALCAVERNS_NAME", "price": 90, "needs": ["SeenMapperCoralCaverns"], "flag": "HasCoralMap"},
    {"item": "Mapper Crawl Map", "vendor": "shakra", "thing": "HasCrawlMap", "name": "MAPPER_ITEM_MAP_CRAWL_NAME", "price": 70, "needs": ["SeenMapperCrawl"], "flag": "HasCrawlMap"},
    {"item": "Mapper Docks Map", "vendor": "shakra", "thing": "HasDocksMap", "name": "MAPPER_ITEM_MAP_DOCKS_NAME", "price": 50, "needs": ["SeenMapperDocks"], "flag": "HasDocksMap"},
    {"item": "Mapper Dustpens Map", "vendor": "shakra", "thing": "HasDustpensMap", "name": "MAPPER_ITEM_MAP_DUSTPENS_NAME", "price": 90, "needs": ["SeenMapperDustpens"], "flag": "HasDustpensMap"},
    {"item": "Mapper Greymoor Map", "vendor": "shakra", "thing": "HasGreymoorMap", "name": "MAPPER_ITEM_MAP_GREYMOOR_NAME", "price": 70, "needs": ["SeenMapperGreymoor"], "flag": "HasGreymoorMap"},
    {"item": "Mapper Hunters Nest Map", "vendor": "shakra", "thing": "HasHuntersNestMap", "name": "MAPPER_ITEM_MAP_HUNTERSNEST_NAME", "price": 70, "needs": ["SeenMapperHuntersNest"], "flag": "HasHuntersNestMap"},
    {"item": "Mapper JudgeSteps Map", "vendor": "shakra", "thing": "HasJudgeStepsMap", "name": "MAPPER_ITEM_MAP_JUDGESTEPS_NAME", "price": 70, "needs": ["SeenMapperJudgeSteps"], "flag": "HasJudgeStepsMap"},
    {"item": "Mapper Map Marker A", "vendor": "shakra", "thing": "hasMarker_a", "name": "MAPPER_ITEM_MARKER_A_NAME", "price": 40, "flag": "hasMarker_a"},
    {"item": "Mapper Map Marker B", "vendor": "shakra", "thing": "hasMarker_b", "name": "MAPPER_ITEM_MARKER_B_NAME", "price": 40, "needs": ["visitedDeepDocks", "visitedCrawl"], "flag": "hasMarker_b"},
    {"item": "Mapper Map Marker C", "vendor": "shakra", "thing": "hasMarker_c", "name": "MAPPER_ITEM_MARKER_C_NAME", "price": 60, "needs": ["SeenMapperHuntersNest", "spinnerDefeated"], "flag": "hasMarker_c"},
    {"item": "Mapper Map Marker D", "vendor": "shakra", "thing": "hasMarker_d", "name": "MAPPER_ITEM_MARKER_D_NAME", "price": 90, "needs": ["visitedCitadel"], "flag": "hasMarker_d"},
    {"item": "Mapper Map Marker E", "vendor": "shakra", "thing": "hasMarker_e", "name": "MAPPER_ITEM_MARKER_E_NAME", "price": 120, "needs": ["visitedCitadel"], "flag": "hasMarker_e"},
    {"item": "Mapper Moss Grotto Map", "vendor": "shakra", "thing": "HasMossGrottoMap", "name": "MAPPER_ITEM_MAP_MOSSGROTTO_NAME", "price": 40, "flag": "HasMossGrottoMap"},
    {"item": "Mapper Peak Map", "vendor": "shakra", "thing": "HasPeakMap", "name": "MAPPER_ITEM_MAP_PEAK_NAME", "price": 40, "needs": ["SeenMapperPeak"], "flag": "HasPeakMap"},
    {"item": "Mapper Quill", "vendor": "shakra", "thing": "hasQuill", "name": "MAPPER_ITEM_QUILL_NAME", "price": 50, "flag": "hasQuill"},
    {"item": "Mapper Shadow Map", "vendor": "shakra", "thing": "HasSwampMap", "name": "MAPPER_ITEM_MAP_SHADOW_NAME", "price": 90, "needs": ["SeenMapperShadow"], "flag": "HasSwampMap"},
    {"item": "Mapper Shellwood Map", "vendor": "shakra", "thing": "HasShellwoodMap", "name": "MAPPER_ITEM_MAP_SHELLWOOD_NAME", "price": 70, "needs": ["SeenMapperShellwood"], "flag": "HasShellwoodMap"},
    {"item": "Mapper Shop Map Pin", "vendor": "shakra", "thing": "hasPinShop", "name": "MAPPER_ITEM_PIN_SHOP_NAME", "price": 80, "needs": ["visitedDeepDocks", "visitedCrawl", "visitedGreymoor"], "flag": "hasPinShop"},
    {"item": "Mapper Tube Map Pin", "vendor": "shakra", "thing": "hasPinTube", "name": "MAPPER_ITEM_TUBE_PIN_NAME", "price": 80, "needs": ["mapperSellingTubePins"], "flag": "hasPinTube"},
    {"item": "Mapper Wilds Map", "vendor": "shakra", "thing": "HasWildsMap", "name": "MAPPER_ITEM_MAP_WILDS_NAME", "price": 50, "needs": ["SeenMapperWilds"], "flag": "HasWildsMap"},
    {"item": "Architect Brolly Spike", "vendor": "twelfth-architect", "tool": "sawtooth-circlet", "name": "BROLLYSPIKE_NAME", "price": 230, "craftmetal": 1, "needs": ["hasBrolly"]},
    {"item": "Architect Cogwork Saw", "vendor": "twelfth-architect", "tool": "cogwork-wheel", "name": "COGWORK_SAW_NAME", "price": 360, "craftmetal": 1},
    {"item": "Architect Key", "vendor": "twelfth-architect", "thing": "Architect Key", "name": "INV_NAME_ARCHITECT_KEY", "price": 110, "flag": "PurchasedArchitectKey"},
    {"item": "Architect Scuttlebrace", "vendor": "twelfth-architect", "tool": "scuttlebrace", "name": "SCUTTLEBRACE_NAME", "price": 140, "craftmetal": 1},
    {"item": "Architect Shard Pouch", "vendor": "twelfth-architect", "thing": "Shard Pouch", "name": "INV_NAME_SHARD_POUCH", "price": 50},
    {"item": "Architect SilkShot", "vendor": "twelfth-architect", "tool": "silkshot", "name": "SILKSHOT_NAME", "price": 130, "craftmetal": 1, "needs": ["ArchitectMentionedWebShot"]},
    {"item": "Architect Tool Kit", "vendor": "twelfth-architect", "piece": 110, "name": "INV_MSG_TOOLKIT", "price": 450, "flag": "PurchasedArchitectToolKit"},
  ];

  const REWARDS = {
    "Ant Trapper": {"piece": 17},
    "Beastfly Hunt": {"piece": 6},
    "Broodmother Hunt": {"thing": "Rosary_Set_Large"},
    "Courier Delivery Bonebottom": {"thing": "Money Reward", "count": 150, "countAct3": 180},
    "Courier Delivery Dustpens Slave": {"thing": "Money Reward", "count": 260, "countAct3": 290},
    "Courier Delivery Fixer": {"thing": "Money Reward", "count": 150, "countAct3": 180},
    "Courier Delivery Fleatopia": {"thing": "Money Reward", "count": 410, "countAct3": 480},
    "Courier Delivery Mask Maker": {"thing": "Money Reward", "count": 560, "countAct3": 650},
    "Courier Delivery Pilgrims Rest": {"thing": "Money Reward", "count": 180, "countAct3": 200},
    "Courier Delivery Songclave": {"thing": "Money Reward", "count": 360, "countAct3": 410},
    "Crow Feathers": {"piece": 108},
    "Destroy Thread Cores": {"piece": 18},
    "Extractor Blue": {"tool": "plasmium-phial"},
    "Extractor Blue Worms": {"thing": "Plasmium Gland"},
    "Fine Pins": {"thing": "Rosary_Set_Large"},
    "Great Gourmand": {"piece": 67},
    "Huntress Quest": {"tool": "longclaw"},
    "Huntress Quest Runt": {"tool": "longclaw"},
    "Journal": {"piece": 105},
    "Pilgrim Rags": {"thing": "Rosary_Set_Medium"},
    "Pinstress Battle": {"tool": "pin-badge"},
    "Roach Killing": {"tool": "tacks"},
    "Rock Rollers": {"piece": 44},
    "Save the Fleas": {"tool": "flea-brew"},
    "Shakra Final Quest": {"tool": "throwing-ring"},
    "Shell Flowers": {"tool": "pollip-pouch"},
    "Shiny Bell Goomba": {"thing": "Rosary_Set_Medium"},
    "Skull King": {"thing": "Rosary_Set_Large"},
    "Song Pilgrim Cloaks": {"thing": "Rosary_Set_Large"},
    "Sprintmaster Race": {"piece": 16},
    "Steel Sentinel Pt2": {"thing": "Growstone"},
  };

  const NEEDLE = {"further": 450, "final": 680};

  const UNSOLD = ["Belltown Tool Pouch", "Forge Tacks Tool", "Grindle Reserve Bind"];

  SS.shop = { VENDORS, SHOP, REWARDS, NEEDLE, UNSOLD };
  if (typeof module !== 'undefined' && module.exports) module.exports = SS.shop;
})();
