"""tools/extract-graph.py — how Pharloom's rooms connect, from the game's own files, into js/graph.js:
for each scene, the scenes its doors lead to. Needs the game installed and UnityPy, as
tools/extract-map.py does:
    uv venv /tmp/unitypy && uv pip install --python /tmp/unitypy/bin/python UnityPy
    /tmp/unitypy/bin/python tools/extract-graph.py "<Steam>/steamapps/common/Hollow Knight Silksong"
Re-run it after a patch that adds or moves rooms.

Where it is (found on 28-Sep-2026): each scene is a bundle of its own in
StreamingAssets/aa/StandaloneLinux64/scenes_scenes_scenes/, named after the scene in lower case,
and every way out of a room is a TransitionPoint (the game's class: a door, an edge, a drop),
whose targetScene is where it leads. Only those components are read: they're told apart by their
MonoScript's path id in the shared monoscripts bundle, without reading every MonoBehaviour's type
tree. A way out can be one-way (a drop, a door that only opens from one side), so the graph is
directed: A → B when A has a way to B. The scenes' own names, with their capitals, come from the
doors that lead to them and from js/map.js; a bundle nobody leads to keeps its lower-case name.
Not in it: the Bellways and the Ventrica, which aren't doors (js/rooms.js adds the stations a
save has opened), and the memories' ways in, which are events. """
import json, os, re, struct, sys
import UnityPy

UnityPy.config.FALLBACK_UNITY_VERSION = '6000.0.50f1'
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
OUT = os.path.join(ROOT, 'js', 'graph.js')


def main(game):
    aa = os.path.join(game, 'Hollow Knight Silksong_Data', 'StreamingAssets', 'aa', 'StandaloneLinux64')
    scenes = os.path.join(aa, 'scenes_scenes_scenes')
    mono = next(os.path.join(aa, f) for f in os.listdir(aa) if f.endswith('_monoscripts.bundle'))
    door = next(o.path_id for o in UnityPy.load(mono).objects
                if o.type.name == 'MonoScript' and o.read().m_ClassName == 'TransitionPoint')
    out = {}
    names = sorted(f[:-7] for f in os.listdir(scenes) if f.endswith('.bundle'))
    for i, name in enumerate(names):
        env = UnityPy.load(os.path.join(scenes, name + '.bundle'))
        to = set()
        for o in env.objects:
            if o.type.name != 'MonoBehaviour':
                continue
            raw = o.get_raw_data()
            if len(raw) < 28 or struct.unpack_from('<q', raw, 20)[0] != door:
                continue
            t = o.read_typetree().get('targetScene') or ''
            if t and t.lower() != name:
                to.add(t)
        out[name] = sorted(to)
        if i % 50 == 0:
            print(f'{i}/{len(names)} {name}', file=sys.stderr, flush=True)
    # The scenes' names with their capitals: from the doors, then from the map.
    proper = {}
    for to in out.values():
        for t in to:
            proper.setdefault(t.lower(), t)
    src = open(os.path.join(ROOT, 'js', 'map.js')).read()
    for k in json.loads(re.search(r'SS\.map = (\{.*\});', src).group(1))['ROOMS']:
        proper.setdefault(k.lower(), k)
    GRAPH = {proper.get(k, k): v for k, v in sorted(out.items()) if v}
    edges = sum(len(v) for v in GRAPH.values())
    data = json.dumps(GRAPH, separators=(',', ':'))
    open(OUT, 'w').write(
        "/* js/graph.js — how the rooms connect: scene → the scenes its ways out lead to.\n"
        "   GENERATED by tools/extract-graph.py from the game's own files (each scene's\n"
        "   TransitionPoints): not edited by hand. Directed: a drop leads one way. The Bellways and\n"
        "   the Ventrica aren't in it (js/rooms.js adds a save's). */\n"
        "(() => {\n  'use strict';\n  const SS = globalThis.SS || (globalThis.SS = {});\n"
        f"  SS.graph = {data};\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = SS.graph;\n})();\n")
    print(f'{len(GRAPH)} scenes with ways out, {edges} ways → js/graph.js ({os.path.getsize(OUT) // 1024} KB)')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit('usage: extract-graph.py "<Steam>/steamapps/common/Hollow Knight Silksong"')
    main(sys.argv[1])
