#!/usr/bin/env node
/* tools/gen-journal.js — generates js/journal.js: the Hunter's Journal, in the game's order,
   with the game's own texts and what each entry needs.
     node tools/gen-journal.js          (npm run data runs it with the other generators)
   Offline: it reads kb/data/raw/ (npm run kb) and the game's text dump.

   Where each thing comes from:
     · order and kills   the wiki's "Hunter's Journal (Silksong)" table, one row per entry in the
                         game's order, with the kills the full entry needs and a note.
     · the texts         the game's own: NAME_<X>, DESC_<X> and the Hunter's NOTE_<X>, joined by
                         each entry's wiki page's CODEname (tools/names.js), not by name.
     · the flags         read from the wiki's notes, which aren't shown (they're English prose):
                         optional (not needed for the Hunter's Memento), Steel Soul only, open from
                         the start, completed by inspecting, and what else completes it. */
'use strict';
const path = require('path');
const W = require('./wiki.js');
const { names } = require('./names.js');
const { write } = require('./emit.js');

const OUT = path.join(__dirname, '..', 'js', 'journal.js');
function fail(msg) { throw new Error('gen-journal: ' + msg); }

/* What else completes an entry, from its note: bosses by their page, and two events. */
function alsoBy(raw) {
  const note = W.plain(raw);
  const by = [];
  const def = /(?:completed by defeating|needs to be defeated)/.test(note);
  if (def) {
    // The links in the note are the bosses ("…by defeating [[Crust King Khann]]"), or the one
    // that must fall ("[[Raging Conchfly]] needs to be defeated").
    for (const m of raw.matchAll(/\[\[([^\]|#]+)/g)) {
      const t = m[1].trim();
      if (/defeating/.test(note) && !new RegExp('defeating\\s+(?:the\\s+)?' + W.plain(t).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i').test(note)) continue;
      by.push(W.slug(t.replace(/ \(Silksong\)$/, '')));
    }
    // "…by defeating The Unravelled" without a link: the text after the words.
    if (!by.length) { const m = /defeating (.+?)\.?$/.exec(note); if (m) by.push(W.slug(m[1])); }
  }
  if (/entering Act 3/.test(note)) by.push('act-3');
  if (/completing Red Memory/.test(note)) by.push('red-memory');
  if (/destroying the source of the Clawmaidens/.test(note)) by.push('clawmaiden-source');
  return by.length ? by : undefined;
}

(async () => {
  const N = await names();
  const rows = W.table(W.page("Hunter's Journal (Silksong)"), '== Hunter\'s Journal entries ==').slice(1);
  const book = rows.map((r, i) => {
    const page = W.linkTarget(r[0].replace(/\[\[File:[^\]]*\]\]/, ''));
    const key = N.journalKey(page);
    const x = key.slice('NAME_'.length);
    const kills = W.plain(r[1]);
    const note = W.plain(r[2] || '');
    const e = {
      n: i + 1,
      id: W.slug(page.replace(/ \(Silksong\)$/, '')),
      key,
      name: N.text(key),
      desc: N.text('DESC_' + x, true) || undefined,
      note: N.text('NOTE_' + x, true) || undefined,
    };
    if (/^\d+$/.test(kills)) e.kills = Number(kills);
    else if (/^1\/2$/.test(kills)) { e.kills = 2; e.killsSkipped = 1; }   // Lace: once in the Cradle if the Deep Docks fight was skipped
    else if (/^Entry$/.test(kills)) { e.kills = null; e.inspect = true; }   // Void Tendrils: a lore tablet
    else fail(`${page}: kills "${kills}"`);
    if (/Not required for Hunter's Memento/.test(note)) e.optional = true;
    if (/Exclusive to Steel Soul/.test(note)) e.steel = true;
    if (/already unlocked after obtaining/.test(note)) e.start = true;
    e.by = alsoBy(r[2] || '');
    return e;
  });

  // The counts the study states (design/00-study.md §3.3): 236 entries, 237 in Steel Soul; six
  // optional; Nuu's reward at 230 (231).
  const classic = book.filter((e) => !e.steel);
  const required = classic.filter((e) => !e.optional).length;
  if (classic.length !== 236 || book.length !== 237 || required !== 230) fail(`${classic.length} entries (${book.length} in Steel Soul), ${required} required`);
  const ids = new Set(book.map((e) => e.id));
  if (ids.size !== book.length) fail('two entries share an id');
  const noText = book.filter((e) => !e.desc || !e.note).map((e) => e.id);

  const header = `js/journal.js — the Hunter's Journal («Diario de caza», INV_NAME_JOURNAL), in the game's order.
   GENERATED by tools/gen-journal.js from kb/data/raw/ (the wiki's "Hunter's Journal (Silksong)",
   fetched with npm run kb) and the game's text (patch 1.0.30000): not edited by hand.

     BOOK     the 237 entries: 236 in a Classic game, plus the Summoned Saviour in Steel Soul.
       n         its place in the Journal.
       id        its wiki page, as js/enemies.js's page: the key into FOES and ATTACKS.
       name, desc, note   the game's NAME_, DESC_ and the Hunter's NOTE_ { es, en, key }.
       kills     defeats the full entry needs; null = it's completed by inspecting (inspect).
                 killsSkipped: Lace's, when her Deep Docks fight was skipped.
       optional  not needed for Nuu's reward, the Hunter's Memento (six: 230 of 236 are needed,
                 231 of 237 in Steel Soul). steel = Steel Soul only. start = open from the start.
       by        what else completes it: a boss's page id, 'act-3', 'red-memory', or
                 'clawmaiden-source' (destroying where the Clawmaidens come from).
     REQUIRED  the entries Nuu's reward needs: { classic, steel }.`;
  const size = write(OUT, header, 'journal', [['BOOK', book], ['REQUIRED', { classic: required, steel: required + 1 }]]);
  console.log(`js/journal.js: ${book.length} entries, ${required} required; without desc or note: ${noText.join(', ') || 'none'} (${(size / 1024).toFixed(1)} KB)`);
})().catch((e) => { console.error(e.message); process.exitCode = 1; });
